/**
 * Generated by tools/build-nutrient-data.py. Do not edit by hand.
 *
 * For each nutrient, the foods in the catalogue that carry the most of
 * it per 100 g — computed from the same USDA records the app ships, not
 * typed out from another website. `frame` is the photograph, cut from
 * the app's food archive and served from /assets/foods/<frame>.webp.
 *
 * Percentages are of the US Daily Value used on the Nutrition Facts
 * label. Spices, supplements, infant formula and fortified products are
 * excluded: a list that opens with dried thyme is correct and useless.
 */

export interface RankedFood {
  readonly name: string;
  /** Amount per 100 g, in the nutrient's unit. */
  readonly amount: number;
  /** Percent of the US Daily Value, per 100 g. */
  readonly percent: number;
  readonly kcal: number | null;
  /** Frame number; the photograph is /assets/foods/<frame>.webp. */
  readonly frame: number;
}

export interface NutrientTable {
  readonly unit: string;
  readonly dailyValue: number;
  readonly foods: readonly RankedFood[];
}

export const NUTRIENT_FOODS: Readonly<Record<string, NutrientTable>> = {
  "vitamin-a": {
    "unit": "µg",
    "dailyValue": 900,
    "foods": [
      {
        "name": "Veal, variety meats and by-products, liver, cooked, braised",
        "amount": 21100.0,
        "percent": 2349,
        "kcal": 192,
        "frame": 9534
      },
      {
        "name": "Beef, New Zealand, imported, variety meats and by-products liver, cooked, boiled",
        "amount": 21000.0,
        "percent": 2335,
        "kcal": 150,
        "frame": 6192
      },
      {
        "name": "Lamb, New Zealand, imported, liver, cooked, soaked and fried",
        "amount": 19900.0,
        "percent": 2208,
        "kcal": 168,
        "frame": 12349
      },
      {
        "name": "Duck, domesticated, liver, raw",
        "amount": 12000.0,
        "percent": 1332,
        "kcal": 136,
        "frame": 13839
      },
      {
        "name": "Turkey, all classes, liver, cooked, simmered",
        "amount": 10800.0,
        "percent": 1195,
        "kcal": 189,
        "frame": 2201
      },
      {
        "name": "Goose, liver, raw",
        "amount": 9310.0,
        "percent": 1034,
        "kcal": 133,
        "frame": 2812
      },
      {
        "name": "Liver, beef",
        "amount": 7680.0,
        "percent": 854,
        "kcal": 174,
        "frame": 7829
      },
      {
        "name": "Pork, fresh, variety meats and by-products, liver, raw",
        "amount": 6500.0,
        "percent": 722,
        "kcal": 134,
        "frame": 3991
      },
      {
        "name": "Liver cheese, pork",
        "amount": 5250.0,
        "percent": 584,
        "kcal": 304,
        "frame": 65
      },
      {
        "name": "Pate, truffle flavor",
        "amount": 4500.0,
        "percent": 501,
        "kcal": 327,
        "frame": 5620
      },
      {
        "name": "Chicken, capons, giblets, raw",
        "amount": 4370.0,
        "percent": 486,
        "kcal": 130,
        "frame": 1333
      },
      {
        "name": "Liverwurst",
        "amount": 4220.0,
        "percent": 469,
        "kcal": 327,
        "frame": 14052
      }
    ]
  },
  "vitamin-c": {
    "unit": "mg",
    "dailyValue": 90,
    "foods": [
      {
        "name": "Acerola, (west indian cherry), raw",
        "amount": 1680.0,
        "percent": 1864,
        "kcal": 32,
        "frame": 2621
      },
      {
        "name": "Acerola juice, raw",
        "amount": 1600.0,
        "percent": 1778,
        "kcal": 23,
        "frame": 3647
      },
      {
        "name": "Rose Hips, wild (Northern Plains Indians)",
        "amount": 426.0,
        "percent": 473,
        "kcal": 162,
        "frame": 6198
      },
      {
        "name": "Rosehip (Mosqueta)",
        "amount": 426.0,
        "percent": 473,
        "kcal": 162,
        "frame": 8311
      },
      {
        "name": "Cassava Leaves (Nsaka)",
        "amount": 310.0,
        "percent": 344,
        "kcal": 71,
        "frame": 6578
      },
      {
        "name": "Peppers, hot chili, green, raw",
        "amount": 242.0,
        "percent": 269,
        "kcal": 40,
        "frame": 8359
      },
      {
        "name": "Chili Peppers (especially Scotch Bonnet)",
        "amount": 242.0,
        "percent": 269,
        "kcal": 40,
        "frame": 9928
      },
      {
        "name": "Scotch Bonnet Peppers",
        "amount": 242.0,
        "percent": 269,
        "kcal": 40,
        "frame": 11532
      },
      {
        "name": "Chili Peppers",
        "amount": 242.0,
        "percent": 269,
        "kcal": 40,
        "frame": 10493
      },
      {
        "name": "Green chili",
        "amount": 242.0,
        "percent": 269,
        "kcal": 32,
        "frame": 5470
      },
      {
        "name": "Guava, raw",
        "amount": 228.0,
        "percent": 254,
        "kcal": 68,
        "frame": 772
      },
      {
        "name": "Guavas, common, raw",
        "amount": 228.0,
        "percent": 254,
        "kcal": 68,
        "frame": 816
      }
    ]
  },
  "vitamin-d": {
    "unit": "µg",
    "dailyValue": 20,
    "foods": [
      {
        "name": "Mushrooms, brown, italian, or crimini, exposed to ultraviolet light, raw",
        "amount": 31.9,
        "percent": 160,
        "kcal": 22,
        "frame": 1547
      },
      {
        "name": "Fish, halibut, Greenland, raw",
        "amount": 27.4,
        "percent": 137,
        "kcal": 186,
        "frame": 7424
      },
      {
        "name": "Mushroom, white, exposed to ultraviolet light, raw",
        "amount": 26.2,
        "percent": 131,
        "kcal": 22,
        "frame": 13092
      },
      {
        "name": "Salmon, sockeye, canned, drained solids, without skin and bones",
        "amount": 21.5,
        "percent": 108,
        "kcal": 158,
        "frame": 1771
      },
      {
        "name": "Sushi, topped with eel",
        "amount": 8.1,
        "percent": 40,
        "kcal": 126,
        "frame": 1830
      },
      {
        "name": "Stewed salmon, Puerto Rican style",
        "amount": 7.6,
        "percent": 38,
        "kcal": 146,
        "frame": 14171
      },
      {
        "name": "Salmon salad",
        "amount": 7.4,
        "percent": 37,
        "kcal": 213,
        "frame": 2067
      },
      {
        "name": "Cheese, American and Swiss blends",
        "amount": 6.5,
        "percent": 32,
        "kcal": 340,
        "frame": 8509
      },
      {
        "name": "Egg, yolk, raw, frozen, pasteurized",
        "amount": 6.0,
        "percent": 30,
        "kcal": 296,
        "frame": 12120
      },
      {
        "name": "Sushi roll, eel",
        "amount": 5.7,
        "percent": 29,
        "kcal": 116,
        "frame": 2735
      },
      {
        "name": "Veal, external fat only, raw",
        "amount": 5.5,
        "percent": 28,
        "kcal": 503,
        "frame": 11144
      },
      {
        "name": "Salmon cake sandwich",
        "amount": 5.2,
        "percent": 26,
        "kcal": 279,
        "frame": 9750
      }
    ]
  },
  "vitamin-e": {
    "unit": "mg",
    "dailyValue": 15,
    "foods": [
      {
        "name": "Wheat germ oil",
        "amount": 149.0,
        "percent": 996,
        "kcal": 884,
        "frame": 9274
      },
      {
        "name": "Sunflower oil",
        "amount": 68.5,
        "percent": 457,
        "kcal": 900,
        "frame": 7907
      },
      {
        "name": "Salad dressing, mayonnaise, regular",
        "amount": 49.7,
        "percent": 331,
        "kcal": 680,
        "frame": 7014
      },
      {
        "name": "Safflower oil",
        "amount": 46.0,
        "percent": 306,
        "kcal": 900,
        "frame": 1139
      },
      {
        "name": "Seeds, sunflower seed butter, with salt added (Includes foods for USDA's Food Distribution Program)",
        "amount": 45.0,
        "percent": 300,
        "kcal": 617,
        "frame": 7443
      },
      {
        "name": "Snacks, popcorn, microwave, regular (butter) flavor, made with partially hydrogenated oil",
        "amount": 40.2,
        "percent": 268,
        "kcal": 557,
        "frame": 9895
      },
      {
        "name": "Almond oil",
        "amount": 39.2,
        "percent": 261,
        "kcal": 884,
        "frame": 12436
      },
      {
        "name": "Cayenne/Red Pepper",
        "amount": 29.8,
        "percent": 199,
        "kcal": 318,
        "frame": 11418
      },
      {
        "name": "Cayenne Pepper",
        "amount": 29.8,
        "percent": 199,
        "kcal": 318,
        "frame": 13848
      },
      {
        "name": "Aleppo Pepper",
        "amount": 29.8,
        "percent": 199,
        "kcal": 318,
        "frame": 7303
      },
      {
        "name": "Cayenne",
        "amount": 29.8,
        "percent": 199,
        "kcal": 318,
        "frame": 7187
      },
      {
        "name": "Dry red chili",
        "amount": 29.8,
        "percent": 199,
        "kcal": 318,
        "frame": 6633
      }
    ]
  },
  "vitamin-k": {
    "unit": "µg",
    "dailyValue": 120,
    "foods": [
      {
        "name": "Amaranth leaves, raw",
        "amount": 1140.0,
        "percent": 950,
        "kcal": 23,
        "frame": 6850
      },
      {
        "name": "Chard, cooked",
        "amount": 866.0,
        "percent": 722,
        "kcal": 44,
        "frame": 10161
      },
      {
        "name": "Dandelion greens, cooked",
        "amount": 812.0,
        "percent": 677,
        "kcal": 71,
        "frame": 2510
      },
      {
        "name": "Yerba Mate (as an ingredient/flavor)",
        "amount": 771.0,
        "percent": 642,
        "kcal": 279,
        "frame": 9715
      },
      {
        "name": "Lemon Ironbark",
        "amount": 771.0,
        "percent": 642,
        "kcal": null,
        "frame": 4562
      },
      {
        "name": "Lemon Myrtle",
        "amount": 771.0,
        "percent": 642,
        "kcal": null,
        "frame": 10496
      },
      {
        "name": "Native Lemongrass",
        "amount": 771.0,
        "percent": 642,
        "kcal": 99,
        "frame": 3389
      },
      {
        "name": "Old Man Saltbush",
        "amount": 771.0,
        "percent": 642,
        "kcal": 344,
        "frame": 5005
      },
      {
        "name": "Strawberry Gum",
        "amount": 771.0,
        "percent": 642,
        "kcal": null,
        "frame": 5197
      },
      {
        "name": "Curry Leaves",
        "amount": 771.0,
        "percent": 642,
        "kcal": 108,
        "frame": 11545
      },
      {
        "name": "Kunzea",
        "amount": 771.0,
        "percent": 642,
        "kcal": null,
        "frame": 9314
      },
      {
        "name": "Lavender",
        "amount": 771.0,
        "percent": 642,
        "kcal": 263,
        "frame": 4029
      }
    ]
  },
  "thiamin": {
    "unit": "mg",
    "dailyValue": 1.2,
    "foods": [
      {
        "name": "Seeds, sunflower seed flour, partially defatted",
        "amount": 3.19,
        "percent": 266,
        "kcal": 326,
        "frame": 13828
      },
      {
        "name": "Veggie burger patty, no bun",
        "amount": 2.65,
        "percent": 221,
        "kcal": 177,
        "frame": 2182
      },
      {
        "name": "Veggie burgers or soyburgers, unprepared",
        "amount": 2.65,
        "percent": 221,
        "kcal": 177,
        "frame": 12015
      },
      {
        "name": "Pasta mix, classic beef, unprepared",
        "amount": 2.36,
        "percent": 197,
        "kcal": 354,
        "frame": 7694
      },
      {
        "name": "Wheat germ, crude",
        "amount": 1.88,
        "percent": 157,
        "kcal": 360,
        "frame": 6044
      },
      {
        "name": "Veggie burger, on bun",
        "amount": 1.68,
        "percent": 140,
        "kcal": 224,
        "frame": 2941
      },
      {
        "name": "Cereals ready-to-eat, wheat germ, toasted, plain",
        "amount": 1.67,
        "percent": 139,
        "kcal": 382,
        "frame": 6724
      },
      {
        "name": "Lamb, New Zealand, imported, liver, cooked, soaked and fried",
        "amount": 1.57,
        "percent": 131,
        "kcal": 168,
        "frame": 12349
      },
      {
        "name": "Corn flour, masa, enriched, white",
        "amount": 1.48,
        "percent": 123,
        "kcal": 363,
        "frame": 14450
      },
      {
        "name": "Thousand Island dressing",
        "amount": 1.45,
        "percent": 120,
        "kcal": 379,
        "frame": 6272
      },
      {
        "name": "Salad dressing, thousand island, commercial, regular",
        "amount": 1.45,
        "percent": 120,
        "kcal": 379,
        "frame": 12851
      },
      {
        "name": "Snacks, crisped rice bar, almond",
        "amount": 1.32,
        "percent": 110,
        "kcal": 458,
        "frame": 226
      }
    ]
  },
  "riboflavin": {
    "unit": "mg",
    "dailyValue": 1.3,
    "foods": [
      {
        "name": "Lamb, New Zealand, imported, liver, cooked, soaked and fried",
        "amount": 5.27,
        "percent": 405,
        "kcal": 168,
        "frame": 12349
      },
      {
        "name": "Beef, variety meats and by-products, liver, cooked, braised",
        "amount": 3.42,
        "percent": 263,
        "kcal": 191,
        "frame": 732
      },
      {
        "name": "Liver, beef",
        "amount": 3.4,
        "percent": 261,
        "kcal": 174,
        "frame": 7829
      },
      {
        "name": "Veal, variety meats and by-products, liver, cooked, pan-fried",
        "amount": 3.06,
        "percent": 235,
        "kcal": 193,
        "frame": 922
      },
      {
        "name": "Pork, fresh, variety meats and by-products, liver, raw",
        "amount": 3.0,
        "percent": 231,
        "kcal": 134,
        "frame": 3991
      },
      {
        "name": "Kidney",
        "amount": 2.95,
        "percent": 227,
        "kcal": 157,
        "frame": 6932
      },
      {
        "name": "Turkey, all classes, liver, cooked, simmered",
        "amount": 2.69,
        "percent": 207,
        "kcal": 189,
        "frame": 2201
      },
      {
        "name": "Chicken, liver, all classes, cooked, pan-fried",
        "amount": 2.31,
        "percent": 178,
        "kcal": 172,
        "frame": 4340
      },
      {
        "name": "Liver cheese, pork",
        "amount": 2.23,
        "percent": 171,
        "kcal": 304,
        "frame": 65
      },
      {
        "name": "Mollusks, cuttlefish, mixed species, cooked, moist heat",
        "amount": 1.73,
        "percent": 133,
        "kcal": 158,
        "frame": 1774
      },
      {
        "name": "Liverwurst",
        "amount": 1.52,
        "percent": 117,
        "kcal": 327,
        "frame": 14052
      },
      {
        "name": "Canada Goose, breast meat only, skinless, raw",
        "amount": 1.52,
        "percent": 117,
        "kcal": 133,
        "frame": 7300
      }
    ]
  },
  "niacin": {
    "unit": "mg",
    "dailyValue": 16,
    "foods": [
      {
        "name": "Peanut flour, defatted",
        "amount": 27.0,
        "percent": 169,
        "kcal": 327,
        "frame": 7898
      },
      {
        "name": "Fish, tuna, cooked",
        "amount": 22.9,
        "percent": 143,
        "kcal": 176,
        "frame": 5248
      },
      {
        "name": "Meat extender",
        "amount": 22.0,
        "percent": 138,
        "kcal": 311,
        "frame": 3098
      },
      {
        "name": "Cereals ready-to-eat, frosted oat cereal with marshmallows",
        "amount": 17.6,
        "percent": 110,
        "kcal": 400,
        "frame": 5549
      },
      {
        "name": "Snacks, crisped rice bar, almond",
        "amount": 17.6,
        "percent": 110,
        "kcal": 458,
        "frame": 226
      },
      {
        "name": "Beef, variety meats and by-products, liver, cooked, braised",
        "amount": 17.5,
        "percent": 110,
        "kcal": 191,
        "frame": 732
      },
      {
        "name": "Liver, beef",
        "amount": 17.3,
        "percent": 108,
        "kcal": 174,
        "frame": 7829
      },
      {
        "name": "Lamb, variety meats and by-products, liver, cooked, pan-fried",
        "amount": 16.7,
        "percent": 104,
        "kcal": 238,
        "frame": 3187
      },
      {
        "name": "Peanut butter, lower sugar",
        "amount": 16.4,
        "percent": 102,
        "kcal": 650,
        "frame": 10937
      },
      {
        "name": "Peanut spread, reduced sugar",
        "amount": 16.4,
        "percent": 102,
        "kcal": 650,
        "frame": 1170
      },
      {
        "name": "Peanuts, spanish, raw",
        "amount": 15.9,
        "percent": 100,
        "kcal": 570,
        "frame": 4372
      },
      {
        "name": "Pork, fresh, variety meats and by-products, liver, raw",
        "amount": 15.3,
        "percent": 96,
        "kcal": 134,
        "frame": 3991
      }
    ]
  },
  "pantothenic-acid": {
    "unit": "mg",
    "dailyValue": 5,
    "foods": [
      {
        "name": "Beef, New Zealand, imported, variety meats and by-products, liver, raw",
        "amount": 10.3,
        "percent": 206,
        "kcal": 133,
        "frame": 7120
      },
      {
        "name": "Chicken, liver, all classes, cooked, pan-fried",
        "amount": 8.31,
        "percent": 166,
        "kcal": 172,
        "frame": 4340
      },
      {
        "name": "Veal, variety meats and by-products, liver, cooked, pan-fried",
        "amount": 7.08,
        "percent": 142,
        "kcal": 193,
        "frame": 922
      },
      {
        "name": "Seeds, sunflower seed kernels, toasted, with salt added",
        "amount": 7.06,
        "percent": 141,
        "kcal": 619,
        "frame": 5634
      },
      {
        "name": "Pork, fresh, variety meats and by-products, liver, raw",
        "amount": 6.65,
        "percent": 133,
        "kcal": 134,
        "frame": 3991
      },
      {
        "name": "Lamb, variety meats and by-products, liver, cooked, pan-fried",
        "amount": 6.33,
        "percent": 127,
        "kcal": 238,
        "frame": 3187
      },
      {
        "name": "Turkey, all classes, liver, raw",
        "amount": 6.28,
        "percent": 126,
        "kcal": 128,
        "frame": 10273
      },
      {
        "name": "Goose, liver, raw",
        "amount": 6.18,
        "percent": 124,
        "kcal": 133,
        "frame": 2812
      },
      {
        "name": "Duck, domesticated, liver, raw",
        "amount": 6.18,
        "percent": 124,
        "kcal": 136,
        "frame": 13839
      },
      {
        "name": "Grape leaves, canned",
        "amount": 4.27,
        "percent": 85,
        "kcal": 69,
        "frame": 14469
      },
      {
        "name": "Emu, full rump, cooked, broiled",
        "amount": 3.65,
        "percent": 73,
        "kcal": 168,
        "frame": 4646
      },
      {
        "name": "Mushrooms, shiitake, cooked, without salt",
        "amount": 3.59,
        "percent": 72,
        "kcal": 56,
        "frame": 10165
      }
    ]
  },
  "vitamin-b6": {
    "unit": "mg",
    "dailyValue": 1.7,
    "foods": [
      {
        "name": "Pasilla chili",
        "amount": 3.73,
        "percent": 219,
        "kcal": 314,
        "frame": 9527
      },
      {
        "name": "Chipotle chili",
        "amount": 3.55,
        "percent": 209,
        "kcal": 289,
        "frame": 14379
      },
      {
        "name": "Urfa Pepper",
        "amount": 3.4,
        "percent": 200,
        "kcal": 318,
        "frame": 12668
      },
      {
        "name": "Piment d’Espelette",
        "amount": 3.39,
        "percent": 199,
        "kcal": 318,
        "frame": 12064
      },
      {
        "name": "Dry red chili",
        "amount": 3.38,
        "percent": 199,
        "kcal": 318,
        "frame": 6633
      },
      {
        "name": "Aleppo Pepper",
        "amount": 3.27,
        "percent": 192,
        "kcal": 318,
        "frame": 7303
      },
      {
        "name": "Byadagi chili",
        "amount": 2.91,
        "percent": 171,
        "kcal": 318,
        "frame": 8417
      },
      {
        "name": "Crushed red pepper",
        "amount": 2.78,
        "percent": 164,
        "kcal": 318,
        "frame": 2728
      },
      {
        "name": "Guntur chili",
        "amount": 2.78,
        "percent": 164,
        "kcal": 318,
        "frame": 7172
      },
      {
        "name": "Kashmiri chili",
        "amount": 2.46,
        "percent": 145,
        "kcal": 318,
        "frame": 6322
      },
      {
        "name": "Cayenne/Red Pepper",
        "amount": 2.45,
        "percent": 144,
        "kcal": 318,
        "frame": 11418
      },
      {
        "name": "Cayenne Pepper",
        "amount": 2.45,
        "percent": 144,
        "kcal": 318,
        "frame": 13848
      }
    ]
  },
  "vitamin-b12": {
    "unit": "µg",
    "dailyValue": 2.4,
    "foods": [
      {
        "name": "Veal, variety meats and by-products, liver, raw",
        "amount": 59.9,
        "percent": 2494,
        "kcal": 140,
        "frame": 7968
      },
      {
        "name": "Beef, variety meats and by-products, liver, raw",
        "amount": 59.3,
        "percent": 2471,
        "kcal": 135,
        "frame": 1340
      },
      {
        "name": "Lamb, New Zealand, imported, liver, raw",
        "amount": 59.0,
        "percent": 2458,
        "kcal": 136,
        "frame": 12582
      },
      {
        "name": "Goose, liver, raw",
        "amount": 54.0,
        "percent": 2250,
        "kcal": 133,
        "frame": 2812
      },
      {
        "name": "Duck, domesticated, liver, raw",
        "amount": 54.0,
        "percent": 2250,
        "kcal": 136,
        "frame": 13839
      },
      {
        "name": "Liver, beef or calves, and onions",
        "amount": 50.7,
        "percent": 2111,
        "kcal": 129,
        "frame": 114
      },
      {
        "name": "Mollusks, clam, mixed species, cooked, breaded and fried",
        "amount": 40.3,
        "percent": 1678,
        "kcal": 202,
        "frame": 666
      },
      {
        "name": "Turkey, all classes, liver, cooked, simmered",
        "amount": 28.2,
        "percent": 1174,
        "kcal": 189,
        "frame": 2201
      },
      {
        "name": "Pork, fresh, variety meats and by-products, liver, raw",
        "amount": 26.0,
        "percent": 1083,
        "kcal": 134,
        "frame": 3991
      },
      {
        "name": "Kidney",
        "amount": 24.7,
        "percent": 1029,
        "kcal": 157,
        "frame": 6932
      },
      {
        "name": "Liver cheese, pork",
        "amount": 24.6,
        "percent": 1023,
        "kcal": 304,
        "frame": 65
      },
      {
        "name": "Chicken, liver, all classes, cooked, pan-fried",
        "amount": 21.1,
        "percent": 880,
        "kcal": 172,
        "frame": 4340
      }
    ]
  },
  "folate": {
    "unit": "µg",
    "dailyValue": 400,
    "foods": [
      {
        "name": "Goose, liver, raw",
        "amount": 738.0,
        "percent": 184,
        "kcal": 133,
        "frame": 2812
      },
      {
        "name": "Duck, domesticated, liver, raw",
        "amount": 738.0,
        "percent": 184,
        "kcal": 136,
        "frame": 13839
      },
      {
        "name": "Turkey, all classes, liver, cooked, simmered",
        "amount": 691.0,
        "percent": 173,
        "kcal": 189,
        "frame": 2201
      },
      {
        "name": "Yardlong beans, mature seeds, raw",
        "amount": 658.0,
        "percent": 164,
        "kcal": 347,
        "frame": 6194
      },
      {
        "name": "Mothbeans, mature seeds, raw",
        "amount": 649.0,
        "percent": 162,
        "kcal": 343,
        "frame": 2760
      },
      {
        "name": "Cowpeas, catjang, mature seeds, raw",
        "amount": 639.0,
        "percent": 160,
        "kcal": 343,
        "frame": 14186
      },
      {
        "name": "Mung beans, mature seeds, raw",
        "amount": 625.0,
        "percent": 156,
        "kcal": 347,
        "frame": 6097
      },
      {
        "name": "Beans, adzuki, mature seeds, raw",
        "amount": 622.0,
        "percent": 156,
        "kcal": 329,
        "frame": 12167
      },
      {
        "name": "Chicken, liver, all classes, raw",
        "amount": 588.0,
        "percent": 147,
        "kcal": 119,
        "frame": 2572
      },
      {
        "name": "Cereals ready-to-eat, frosted oat cereal with marshmallows",
        "amount": 587.0,
        "percent": 147,
        "kcal": 400,
        "frame": 5549
      },
      {
        "name": "Liver, chicken",
        "amount": 580.0,
        "percent": 145,
        "kcal": 189,
        "frame": 8305
      },
      {
        "name": "Chickpeas (garbanzo beans, bengal gram), mature seeds, raw",
        "amount": 557.0,
        "percent": 139,
        "kcal": 378,
        "frame": 2262
      }
    ]
  },
  "choline": {
    "unit": "mg",
    "dailyValue": 550,
    "foods": [
      {
        "name": "Egg, yolk only, raw",
        "amount": 820.0,
        "percent": 149,
        "kcal": 328,
        "frame": 12269
      },
      {
        "name": "Beef, variety meats and by-products, kidneys, cooked, simmered",
        "amount": 513.0,
        "percent": 93,
        "kcal": 158,
        "frame": 5099
      },
      {
        "name": "Kidney",
        "amount": 509.0,
        "percent": 93,
        "kcal": 157,
        "frame": 6932
      },
      {
        "name": "Caviar",
        "amount": 491.0,
        "percent": 89,
        "kcal": 264,
        "frame": 12689
      },
      {
        "name": "Fish, caviar, black and red, granular",
        "amount": 491.0,
        "percent": 89,
        "kcal": 264,
        "frame": 9231
      },
      {
        "name": "Brains",
        "amount": 487.0,
        "percent": 89,
        "kcal": 150,
        "frame": 11288
      },
      {
        "name": "Pork, fresh, variety meats and by-products, chitterlings, cooked, simmered",
        "amount": 471.0,
        "percent": 86,
        "kcal": 233,
        "frame": 256
      },
      {
        "name": "Chitterlings",
        "amount": 467.0,
        "percent": 85,
        "kcal": 231,
        "frame": 9250
      },
      {
        "name": "Liver, beef",
        "amount": 415.0,
        "percent": 75,
        "kcal": 174,
        "frame": 7829
      },
      {
        "name": "Veal, variety meats and by-products, liver, cooked, pan-fried",
        "amount": 411.0,
        "percent": 75,
        "kcal": 193,
        "frame": 922
      },
      {
        "name": "Chicken, liver, all classes, cooked, pan-fried",
        "amount": 327.0,
        "percent": 59,
        "kcal": 172,
        "frame": 4340
      },
      {
        "name": "Hog maws",
        "amount": 307.0,
        "percent": 56,
        "kcal": 250,
        "frame": 3496
      }
    ]
  },
  "calcium": {
    "unit": "mg",
    "dailyValue": 1300,
    "foods": [
      {
        "name": "Nigella seed",
        "amount": 1860.0,
        "percent": 143,
        "kcal": 344,
        "frame": 14361
      },
      {
        "name": "Lovage seed (you had lovage leaf, but not seed)",
        "amount": 1780.0,
        "percent": 137,
        "kcal": 401,
        "frame": 8056
      },
      {
        "name": "Old Man Saltbush",
        "amount": 1700.0,
        "percent": 131,
        "kcal": 344,
        "frame": 5005
      },
      {
        "name": "Kasuri methi",
        "amount": 1700.0,
        "percent": 131,
        "kcal": 323,
        "frame": 367
      },
      {
        "name": "Poppy Seeds",
        "amount": 1440.0,
        "percent": 111,
        "kcal": 525,
        "frame": 12318
      },
      {
        "name": "Poppy Seeds (Mohn)",
        "amount": 1440.0,
        "percent": 111,
        "kcal": 525,
        "frame": 6681
      },
      {
        "name": "Poppy Seeds (Posto)",
        "amount": 1440.0,
        "percent": 111,
        "kcal": 525,
        "frame": 4317
      },
      {
        "name": "Poppy seed (Posto)",
        "amount": 1440.0,
        "percent": 111,
        "kcal": 525,
        "frame": 6873
      },
      {
        "name": "Cheese, processed cheese food",
        "amount": 1380.0,
        "percent": 106,
        "kcal": 307,
        "frame": 8168
      },
      {
        "name": "Carom seed",
        "amount": 1340.0,
        "percent": 103,
        "kcal": 333,
        "frame": 489
      },
      {
        "name": "Chinese Five Spice",
        "amount": 1260.0,
        "percent": 97,
        "kcal": 269,
        "frame": 461
      },
      {
        "name": "Toasted sesame seed",
        "amount": 1260.0,
        "percent": 97,
        "kcal": 615,
        "frame": 11802
      }
    ]
  },
  "iron": {
    "unit": "mg",
    "dailyValue": 18,
    "foods": [
      {
        "name": "Beef, variety meats and by-products, spleen, raw",
        "amount": 44.5,
        "percent": 247,
        "kcal": 105,
        "frame": 3029
      },
      {
        "name": "Lovage seed (you had lovage leaf, but not seed)",
        "amount": 44.0,
        "percent": 244,
        "kcal": 401,
        "frame": 8056
      },
      {
        "name": "Bay Leaves",
        "amount": 43.0,
        "percent": 239,
        "kcal": 313,
        "frame": 13671
      },
      {
        "name": "Laurel",
        "amount": 43.0,
        "percent": 239,
        "kcal": 313,
        "frame": 10562
      },
      {
        "name": "Lamb, variety meats and by-products, spleen, raw",
        "amount": 41.9,
        "percent": 233,
        "kcal": 101,
        "frame": 433
      },
      {
        "name": "Kasuri methi",
        "amount": 41.0,
        "percent": 228,
        "kcal": 323,
        "frame": 367
      },
      {
        "name": "Chinese Five Spice",
        "amount": 38.6,
        "percent": 215,
        "kcal": 269,
        "frame": 461
      },
      {
        "name": "Anise",
        "amount": 37.0,
        "percent": 205,
        "kcal": 337,
        "frame": 7490
      },
      {
        "name": "Five-spice components",
        "amount": 36.9,
        "percent": 205,
        "kcal": 269,
        "frame": 11695
      },
      {
        "name": "Berbere spice",
        "amount": 35.8,
        "percent": 199,
        "kcal": 374,
        "frame": 9871
      },
      {
        "name": "Mitmita",
        "amount": 35.8,
        "percent": 199,
        "kcal": 374,
        "frame": 4191
      },
      {
        "name": "Chemen (spice mix)",
        "amount": 33.5,
        "percent": 186,
        "kcal": 323,
        "frame": 2170
      }
    ]
  },
  "magnesium": {
    "unit": "mg",
    "dailyValue": 420,
    "foods": [
      {
        "name": "Seeds, hemp seed, hulled",
        "amount": 700.0,
        "percent": 167,
        "kcal": 553,
        "frame": 12570
      },
      {
        "name": "Wheat bran",
        "amount": 611.0,
        "percent": 145,
        "kcal": 216,
        "frame": 9179
      },
      {
        "name": "Pepita spice (ground pumpkin seeds)",
        "amount": 592.0,
        "percent": 141,
        "kcal": 574,
        "frame": 11723
      },
      {
        "name": "Pumpkin seeds, NFS",
        "amount": 550.0,
        "percent": 131,
        "kcal": 574,
        "frame": 11716
      },
      {
        "name": "Soy flour, full-fat, raw",
        "amount": 429.0,
        "percent": 102,
        "kcal": 434,
        "frame": 3484
      },
      {
        "name": "Old Man Saltbush",
        "amount": 400.0,
        "percent": 95,
        "kcal": 344,
        "frame": 5005
      },
      {
        "name": "Fennel Seed (Mouri)",
        "amount": 385.0,
        "percent": 92,
        "kcal": 345,
        "frame": 13922
      },
      {
        "name": "Fennel seed (for seafood)",
        "amount": 385.0,
        "percent": 92,
        "kcal": 345,
        "frame": 4323
      },
      {
        "name": "Annatto seed",
        "amount": 384.0,
        "percent": 91,
        "kcal": 370,
        "frame": 13184
      },
      {
        "name": "Mothbeans, mature seeds, raw",
        "amount": 381.0,
        "percent": 91,
        "kcal": 343,
        "frame": 2760
      },
      {
        "name": "Brazil nuts",
        "amount": 376.0,
        "percent": 90,
        "kcal": 659,
        "frame": 11584
      },
      {
        "name": "Flax seeds",
        "amount": 372.0,
        "percent": 89,
        "kcal": 545,
        "frame": 10709
      }
    ]
  },
  "phosphorus": {
    "unit": "mg",
    "dailyValue": 1250,
    "foods": [
      {
        "name": "Seeds, hemp seed, hulled",
        "amount": 1650.0,
        "percent": 132,
        "kcal": 553,
        "frame": 12570
      },
      {
        "name": "Pumpkin seeds, NFS",
        "amount": 1170.0,
        "percent": 94,
        "kcal": 574,
        "frame": 11716
      },
      {
        "name": "Pepita spice (ground pumpkin seeds)",
        "amount": 1170.0,
        "percent": 94,
        "kcal": 574,
        "frame": 11723
      },
      {
        "name": "Mixed seeds",
        "amount": 1160.0,
        "percent": 93,
        "kcal": 580,
        "frame": 5666
      },
      {
        "name": "Sunflower seeds, plain, unsalted",
        "amount": 1160.0,
        "percent": 92,
        "kcal": 582,
        "frame": 6167
      },
      {
        "name": "Wheat germ",
        "amount": 1150.0,
        "percent": 92,
        "kcal": 382,
        "frame": 2810
      },
      {
        "name": "Cereals ready-to-eat, wheat germ, toasted, plain",
        "amount": 1150.0,
        "percent": 92,
        "kcal": 382,
        "frame": 6724
      },
      {
        "name": "Wheat bran",
        "amount": 1010.0,
        "percent": 81,
        "kcal": 216,
        "frame": 9179
      },
      {
        "name": "Melon Seeds (egusi)",
        "amount": 940.0,
        "percent": 75,
        "kcal": 590,
        "frame": 3
      },
      {
        "name": "Cheese spread, American or Cheddar cheese base, reduced fat",
        "amount": 931.0,
        "percent": 74,
        "kcal": 176,
        "frame": 1805
      },
      {
        "name": "Poppy Seeds",
        "amount": 870.0,
        "percent": 70,
        "kcal": 525,
        "frame": 12318
      },
      {
        "name": "Poppy Seeds (Mohn)",
        "amount": 870.0,
        "percent": 70,
        "kcal": 525,
        "frame": 6681
      }
    ]
  },
  "potassium": {
    "unit": "mg",
    "dailyValue": 4700,
    "foods": [
      {
        "name": "Soy flour, full-fat, raw",
        "amount": 2520.0,
        "percent": 54,
        "kcal": 434,
        "frame": 3484
      },
      {
        "name": "Soy meal, defatted, raw",
        "amount": 2490.0,
        "percent": 53,
        "kcal": 337,
        "frame": 3257
      },
      {
        "name": "Akudjura (Bush Tomato)",
        "amount": 2120.0,
        "percent": 45,
        "kcal": 276,
        "frame": 5670
      },
      {
        "name": "Cayenne/Red Pepper",
        "amount": 2010.0,
        "percent": 43,
        "kcal": 318,
        "frame": 11418
      },
      {
        "name": "Cayenne Pepper",
        "amount": 2010.0,
        "percent": 43,
        "kcal": 318,
        "frame": 13848
      },
      {
        "name": "Aleppo Pepper",
        "amount": 2010.0,
        "percent": 43,
        "kcal": 318,
        "frame": 7303
      },
      {
        "name": "Urfa Pepper",
        "amount": 2010.0,
        "percent": 43,
        "kcal": 318,
        "frame": 12668
      },
      {
        "name": "Dry red chili",
        "amount": 2010.0,
        "percent": 43,
        "kcal": 318,
        "frame": 6633
      },
      {
        "name": "Crushed red pepper",
        "amount": 2010.0,
        "percent": 43,
        "kcal": 318,
        "frame": 2728
      },
      {
        "name": "Piment d’Espelette",
        "amount": 2010.0,
        "percent": 43,
        "kcal": 318,
        "frame": 12064
      },
      {
        "name": "Guntur chili",
        "amount": 2010.0,
        "percent": 43,
        "kcal": 318,
        "frame": 7172
      },
      {
        "name": "Chipotle chili (smoked)",
        "amount": 2010.0,
        "percent": 43,
        "kcal": 318,
        "frame": 13863
      }
    ]
  },
  "zinc": {
    "unit": "mg",
    "dailyValue": 11,
    "foods": [
      {
        "name": "Oysters, canned",
        "amount": 98.9,
        "percent": 899,
        "kcal": 74,
        "frame": 12742
      },
      {
        "name": "Mollusks, oyster, eastern, canned",
        "amount": 91.0,
        "percent": 827,
        "kcal": 68,
        "frame": 3118
      },
      {
        "name": "Oysters Rockefeller",
        "amount": 18.8,
        "percent": 171,
        "kcal": 134,
        "frame": 3149
      },
      {
        "name": "Wheat germ",
        "amount": 16.7,
        "percent": 152,
        "kcal": 382,
        "frame": 2810
      },
      {
        "name": "Cereals ready-to-eat, wheat germ, toasted, plain",
        "amount": 16.7,
        "percent": 152,
        "kcal": 382,
        "frame": 6724
      },
      {
        "name": "Beef, chuck, short ribs, boneless, separable lean only, trimmed to 0\" fat, select, cooked, braised",
        "amount": 12.3,
        "percent": 112,
        "kcal": 224,
        "frame": 6017
      },
      {
        "name": "Veal, variety meats and by-products, liver, raw",
        "amount": 12.0,
        "percent": 109,
        "kcal": 140,
        "frame": 7968
      },
      {
        "name": "Seeds, sesame flour, partially defatted",
        "amount": 10.7,
        "percent": 97,
        "kcal": 382,
        "frame": 8719
      },
      {
        "name": "Bear",
        "amount": 10.2,
        "percent": 93,
        "kcal": 257,
        "frame": 5839
      },
      {
        "name": "Dressing with oysters",
        "amount": 10.0,
        "percent": 91,
        "kcal": 189,
        "frame": 2805
      },
      {
        "name": "Baking chocolate, unsweetened, squares",
        "amount": 9.63,
        "percent": 88,
        "kcal": 642,
        "frame": 13118
      },
      {
        "name": "Hyacinth beans, mature seeds, raw",
        "amount": 9.3,
        "percent": 85,
        "kcal": 344,
        "frame": 10279
      }
    ]
  },
  "copper": {
    "unit": "mg",
    "dailyValue": 0.9,
    "foods": [
      {
        "name": "Veal, variety meats and by-products, liver, cooked, pan-fried",
        "amount": 15.1,
        "percent": 1672,
        "kcal": 193,
        "frame": 922
      },
      {
        "name": "Beef, variety meats and by-products, liver, cooked, pan-fried",
        "amount": 14.6,
        "percent": 1621,
        "kcal": 175,
        "frame": 2414
      },
      {
        "name": "Liver, beef",
        "amount": 14.5,
        "percent": 1608,
        "kcal": 174,
        "frame": 7829
      },
      {
        "name": "Lamb, New Zealand, imported, liver, cooked, soaked and fried",
        "amount": 13.4,
        "percent": 1489,
        "kcal": 168,
        "frame": 12349
      },
      {
        "name": "Goose, liver, raw",
        "amount": 7.52,
        "percent": 836,
        "kcal": 133,
        "frame": 2812
      },
      {
        "name": "Duck, domesticated, liver, raw",
        "amount": 5.96,
        "percent": 662,
        "kcal": 136,
        "frame": 13839
      },
      {
        "name": "Mollusks, oyster, eastern, wild, cooked, moist heat",
        "amount": 5.71,
        "percent": 634,
        "kcal": 102,
        "frame": 8911
      },
      {
        "name": "Oysters, canned",
        "amount": 4.85,
        "percent": 539,
        "kcal": 74,
        "frame": 12742
      },
      {
        "name": "Seeds, sesame butter, paste",
        "amount": 4.21,
        "percent": 468,
        "kcal": 586,
        "frame": 1297
      },
      {
        "name": "Toasted sesame seed",
        "amount": 4.08,
        "percent": 454,
        "kcal": 615,
        "frame": 11802
      },
      {
        "name": "White sesame",
        "amount": 4.08,
        "percent": 454,
        "kcal": 573,
        "frame": 12918
      },
      {
        "name": "Black sesame",
        "amount": 4.08,
        "percent": 454,
        "kcal": 573,
        "frame": 4933
      }
    ]
  },
  "manganese": {
    "unit": "mg",
    "dailyValue": 2.3,
    "foods": [
      {
        "name": "Cereals ready-to-eat, wheat germ, toasted, plain",
        "amount": 20.0,
        "percent": 868,
        "kcal": 382,
        "frame": 6724
      },
      {
        "name": "Ras el hanout spices (components)",
        "amount": 17.5,
        "percent": 761,
        "kcal": 374,
        "frame": 13727
      },
      {
        "name": "Baharat (Bzar)",
        "amount": 15.0,
        "percent": 652,
        "kcal": 306,
        "frame": 5596
      },
      {
        "name": "Wheat germ, crude",
        "amount": 13.3,
        "percent": 578,
        "kcal": 360,
        "frame": 6044
      },
      {
        "name": "Nuts, hazelnuts or filberts, blanched",
        "amount": 12.7,
        "percent": 550,
        "kcal": 629,
        "frame": 6790
      },
      {
        "name": "Berbere spice",
        "amount": 11.5,
        "percent": 500,
        "kcal": 374,
        "frame": 9871
      },
      {
        "name": "Mitmita",
        "amount": 11.5,
        "percent": 500,
        "kcal": 374,
        "frame": 4191
      },
      {
        "name": "Timur (Sichuan pepper)",
        "amount": 10.1,
        "percent": 439,
        "kcal": 372,
        "frame": 8279
      },
      {
        "name": "Mango, dried, sweetened",
        "amount": 10.0,
        "percent": 435,
        "kcal": 319,
        "frame": 11351
      },
      {
        "name": "Long Pepper (Pipli)",
        "amount": 9.3,
        "percent": 404,
        "kcal": 304,
        "frame": 5091
      },
      {
        "name": "Teff, uncooked",
        "amount": 9.24,
        "percent": 402,
        "kcal": 367,
        "frame": 2732
      },
      {
        "name": "Bay Leaves",
        "amount": 8.17,
        "percent": 355,
        "kcal": 313,
        "frame": 13671
      }
    ]
  },
  "selenium": {
    "unit": "µg",
    "dailyValue": 55,
    "foods": [
      {
        "name": "Pork, fresh, variety meats and by-products, kidneys, cooked, braised",
        "amount": 312.0,
        "percent": 566,
        "kcal": 151,
        "frame": 5085
      },
      {
        "name": "Lamb, variety meats and by-products, kidneys, cooked, braised",
        "amount": 219.0,
        "percent": 398,
        "kcal": 137,
        "frame": 2798
      },
      {
        "name": "Mustard (Black, Yellow, and Brown seeds)[3]",
        "amount": 200.0,
        "percent": 364,
        "kcal": 508,
        "frame": 12737
      },
      {
        "name": "Beef, variety meats and by-products, kidneys, cooked, simmered",
        "amount": 168.0,
        "percent": 305,
        "kcal": 158,
        "frame": 5099
      },
      {
        "name": "Kidney",
        "amount": 167.0,
        "percent": 303,
        "kcal": 157,
        "frame": 6932
      },
      {
        "name": "Black mustard",
        "amount": 164.0,
        "percent": 298,
        "kcal": 508,
        "frame": 6058
      },
      {
        "name": "Mollusks, oyster, Pacific, cooked, moist heat",
        "amount": 154.0,
        "percent": 280,
        "kcal": 163,
        "frame": 5056
      },
      {
        "name": "Mixed nuts, unroasted",
        "amount": 147.0,
        "percent": 267,
        "kcal": 616,
        "frame": 5978
      },
      {
        "name": "Turkey, young hen, skin only, cooked, roasted",
        "amount": 144.0,
        "percent": 262,
        "kcal": 482,
        "frame": 7771
      },
      {
        "name": "Flax seeds",
        "amount": 136.0,
        "percent": 247,
        "kcal": 545,
        "frame": 10709
      },
      {
        "name": "Fish, tuna, cooked",
        "amount": 112.0,
        "percent": 205,
        "kcal": 176,
        "frame": 5248
      },
      {
        "name": "Seeds, sunflower seed butter, with salt added (Includes foods for USDA's Food Distribution Program)",
        "amount": 104.0,
        "percent": 190,
        "kcal": 617,
        "frame": 7443
      }
    ]
  },
  "protein": {
    "unit": "g",
    "dailyValue": 50,
    "foods": [
      {
        "name": "Pork skin rinds",
        "amount": 61.3,
        "percent": 123,
        "kcal": 544,
        "frame": 1961
      },
      {
        "name": "Snacks, pork skins, plain",
        "amount": 61.3,
        "percent": 123,
        "kcal": 544,
        "frame": 4180
      },
      {
        "name": "Peanut flour, defatted",
        "amount": 52.2,
        "percent": 104,
        "kcal": 327,
        "frame": 7898
      },
      {
        "name": "Soy flour, defatted",
        "amount": 51.5,
        "percent": 103,
        "kcal": 327,
        "frame": 11051
      },
      {
        "name": "Seeds, sesame flour, low-fat",
        "amount": 50.1,
        "percent": 100,
        "kcal": 333,
        "frame": 927
      },
      {
        "name": "Soy meal, defatted, raw",
        "amount": 49.2,
        "percent": 98,
        "kcal": 337,
        "frame": 3257
      },
      {
        "name": "Mollusks, whelk, unspecified, cooked, moist heat",
        "amount": 47.7,
        "percent": 95,
        "kcal": 275,
        "frame": 515
      },
      {
        "name": "Pork, cracklings",
        "amount": 45.0,
        "percent": 90,
        "kcal": 569,
        "frame": 6586
      },
      {
        "name": "Meat extender",
        "amount": 41.7,
        "percent": 83,
        "kcal": 311,
        "frame": 3098
      },
      {
        "name": "Cheese, parmesan, low sodium",
        "amount": 41.6,
        "percent": 83,
        "kcal": 451,
        "frame": 6761
      },
      {
        "name": "Parmesan cheese topping, fat free",
        "amount": 40.0,
        "percent": 80,
        "kcal": 370,
        "frame": 3535
      },
      {
        "name": "Bacon, for use on a sandwich",
        "amount": 39.4,
        "percent": 79,
        "kcal": 494,
        "frame": 6317
      }
    ]
  },
  "fibre": {
    "unit": "g",
    "dailyValue": 28,
    "foods": [
      {
        "name": "Pinon Nuts, roasted (Navajo)",
        "amount": 43.4,
        "percent": 155,
        "kcal": 541,
        "frame": 389
      },
      {
        "name": "Wheat bran",
        "amount": 42.8,
        "percent": 153,
        "kcal": 216,
        "frame": 9179
      },
      {
        "name": "Nigella Seed (Kalonji)",
        "amount": 40.0,
        "percent": 143,
        "kcal": 345,
        "frame": 13343
      },
      {
        "name": "Nigella seed",
        "amount": 40.0,
        "percent": 143,
        "kcal": 344,
        "frame": 14361
      },
      {
        "name": "Carob flour",
        "amount": 39.8,
        "percent": 142,
        "kcal": 222,
        "frame": 7750
      },
      {
        "name": "Fennel Seed (Mouri)",
        "amount": 39.8,
        "percent": 142,
        "kcal": 345,
        "frame": 13922
      },
      {
        "name": "Fennel seed (for seafood)",
        "amount": 39.8,
        "percent": 142,
        "kcal": 345,
        "frame": 4323
      },
      {
        "name": "Sichuan pepper",
        "amount": 39.8,
        "percent": 142,
        "kcal": 372,
        "frame": 10531
      },
      {
        "name": "Andaliman (Sichuan pepper–like)",
        "amount": 39.8,
        "percent": 142,
        "kcal": 371,
        "frame": 4214
      },
      {
        "name": "Sichuan pepper (Timur)",
        "amount": 39.4,
        "percent": 141,
        "kcal": 372,
        "frame": 14474
      },
      {
        "name": "Caraway Seed (Kümmel)",
        "amount": 38.0,
        "percent": 136,
        "kcal": 333,
        "frame": 12627
      },
      {
        "name": "Sumac",
        "amount": 36.2,
        "percent": 129,
        "kcal": 339,
        "frame": 4927
      }
    ]
  }
};
