/**
 * Generated by tools/build-nutrient-data.py. Do not edit by hand.
 *
 * For each nutrient, the foods in the catalogue that carry the most of
 * it per 100 g — computed from the same USDA records the app ships, not
 * typed out from another website. `frame` is the photograph, cut from
 * the app's food archive and served from /assets/foods/<frame>.webp.
 *
 * Percentages are of the US Daily Value used on the Nutrition Facts
 * label. Spices, supplements, infant formula and fortified products are
 * excluded: a list that opens with dried thyme is correct and useless.
 */

export interface RankedFood {
  readonly name: string;
  /** Amount per 100 g, in the nutrient's unit. */
  readonly amount: number;
  /** Percent of the US Daily Value, per 100 g. */
  readonly percent: number;
  readonly kcal: number | null;
  /** Frame number; the photograph is /assets/foods/<frame>.webp. */
  readonly frame: number;
}

export interface NutrientTable {
  readonly unit: string;
  readonly dailyValue: number;
  readonly foods: readonly RankedFood[];
}

export const NUTRIENT_FOODS: Readonly<Record<string, NutrientTable>> = {
  "vitamin-a": {
    "unit": "µg",
    "dailyValue": 900,
    "foods": [
      {
        "name": "Veal, variety meats and by-products, liver, cooked, braised",
        "amount": 21100.0,
        "percent": 2349,
        "kcal": 192,
        "frame": 9534
      },
      {
        "name": "Turkey, whole, giblets, cooked, simmered",
        "amount": 4620.0,
        "percent": 513,
        "kcal": 173,
        "frame": 10875
      },
      {
        "name": "Pate, truffle flavor",
        "amount": 4500.0,
        "percent": 501,
        "kcal": 327,
        "frame": 5620
      },
      {
        "name": "Liverwurst",
        "amount": 4220.0,
        "percent": 469,
        "kcal": 327,
        "frame": 14052
      },
      {
        "name": "Grape leaves, raw",
        "amount": 1380.0,
        "percent": 153,
        "kcal": 93,
        "frame": 6579
      },
      {
        "name": "Sweet potato, frozen, cooked, baked, without salt",
        "amount": 1040.0,
        "percent": 116,
        "kcal": 100,
        "frame": 12633
      },
      {
        "name": "Fish, eel, mixed species, raw",
        "amount": 1040.0,
        "percent": 116,
        "kcal": 184,
        "frame": 8408
      },
      {
        "name": "Carrot juice, 100%",
        "amount": 956.0,
        "percent": 106,
        "kcal": 40,
        "frame": 3557
      },
      {
        "name": "Ghee (Clarified Butter)",
        "amount": 859.0,
        "percent": 95,
        "kcal": 899,
        "frame": 4119
      },
      {
        "name": "Pumpkin, canned, without salt",
        "amount": 778.0,
        "percent": 86,
        "kcal": 34,
        "frame": 5651
      },
      {
        "name": "Dandelion greens, cooked, boiled, drained, with salt",
        "amount": 727.0,
        "percent": 81,
        "kcal": 33,
        "frame": 80
      },
      {
        "name": "Garlic sauce",
        "amount": 682.0,
        "percent": 76,
        "kcal": 683,
        "frame": 1237
      }
    ]
  },
  "vitamin-c": {
    "unit": "mg",
    "dailyValue": 90,
    "foods": [
      {
        "name": "Acerola, (west indian cherry), raw",
        "amount": 1680.0,
        "percent": 1864,
        "kcal": 32,
        "frame": 2621
      },
      {
        "name": "Rosehip (Mosqueta)",
        "amount": 426.0,
        "percent": 473,
        "kcal": 162,
        "frame": 8311
      },
      {
        "name": "Cassava Leaves (Nsaka)",
        "amount": 310.0,
        "percent": 344,
        "kcal": 71,
        "frame": 6578
      },
      {
        "name": "Guava, raw",
        "amount": 228.0,
        "percent": 254,
        "kcal": 68,
        "frame": 772
      },
      {
        "name": "Peppers, sweet, yellow, raw",
        "amount": 184.0,
        "percent": 204,
        "kcal": 27,
        "frame": 4408
      },
      {
        "name": "Currants, european black, raw",
        "amount": 181.0,
        "percent": 201,
        "kcal": 63,
        "frame": 10159
      },
      {
        "name": "Kiwifruit, ZESPRI SunGold, raw",
        "amount": 161.0,
        "percent": 179,
        "kcal": 63,
        "frame": 12980
      },
      {
        "name": "Orange juice, 100%, frozen, not reconstituted",
        "amount": 145.0,
        "percent": 161,
        "kcal": 148,
        "frame": 9018
      },
      {
        "name": "Drumstick pods, raw",
        "amount": 141.0,
        "percent": 157,
        "kcal": 37,
        "frame": 3014
      },
      {
        "name": "Mustard spinach, (tendergreen), raw",
        "amount": 130.0,
        "percent": 144,
        "kcal": 22,
        "frame": 2632
      },
      {
        "name": "Lemon peel, raw",
        "amount": 129.0,
        "percent": 143,
        "kcal": 47,
        "frame": 12941
      },
      {
        "name": "Davidson's Plum",
        "amount": 120.0,
        "percent": 133,
        "kcal": 55,
        "frame": 2476
      }
    ]
  },
  "vitamin-d": {
    "unit": "µg",
    "dailyValue": 20,
    "foods": [
      {
        "name": "Mushrooms, brown, italian, or crimini, exposed to ultraviolet light, raw",
        "amount": 31.9,
        "percent": 160,
        "kcal": 22,
        "frame": 1547
      },
      {
        "name": "Fish, halibut, Greenland, raw",
        "amount": 27.4,
        "percent": 137,
        "kcal": 186,
        "frame": 7424
      },
      {
        "name": "Salmon, sockeye, canned, drained solids, without skin and bones",
        "amount": 21.5,
        "percent": 108,
        "kcal": 158,
        "frame": 1771
      },
      {
        "name": "Sushi, topped with eel",
        "amount": 8.1,
        "percent": 40,
        "kcal": 126,
        "frame": 1830
      },
      {
        "name": "Cheese, American and Swiss blends",
        "amount": 6.5,
        "percent": 32,
        "kcal": 340,
        "frame": 8509
      },
      {
        "name": "Egg, yolk, raw, frozen, pasteurized",
        "amount": 6.0,
        "percent": 30,
        "kcal": 296,
        "frame": 12120
      },
      {
        "name": "Ceviche",
        "amount": 5.1,
        "percent": 26,
        "kcal": 63,
        "frame": 455
      },
      {
        "name": "Anchovies",
        "amount": 4.1,
        "percent": 20,
        "kcal": 210,
        "frame": 11632
      },
      {
        "name": "Ghee (Clarified Butter)",
        "amount": 2.8,
        "percent": 14,
        "kcal": 899,
        "frame": 4119
      },
      {
        "name": "Pork, fresh, spareribs, separable lean and fat, cooked, braised",
        "amount": 2.6,
        "percent": 13,
        "kcal": 397,
        "frame": 7677
      },
      {
        "name": "Flounder with crab stuffing",
        "amount": 2.5,
        "percent": 12,
        "kcal": 136,
        "frame": 790
      },
      {
        "name": "Nutritional drink or shake, liquid, soy-based",
        "amount": 2.3,
        "percent": 12,
        "kcal": 138,
        "frame": 7419
      }
    ]
  },
  "vitamin-e": {
    "unit": "mg",
    "dailyValue": 15,
    "foods": [
      {
        "name": "Seeds, sunflower seed butter, with salt added",
        "amount": 45.0,
        "percent": 300,
        "kcal": 617,
        "frame": 7443
      },
      {
        "name": "Nuts, pecans",
        "amount": 26.7,
        "percent": 178,
        "kcal": 691,
        "frame": 5674
      },
      {
        "name": "Almonds, unroasted",
        "amount": 25.6,
        "percent": 171,
        "kcal": 626,
        "frame": 3612
      },
      {
        "name": "Fruit juice, acai blend",
        "amount": 22.2,
        "percent": 148,
        "kcal": 62,
        "frame": 14131
      },
      {
        "name": "Mixed seeds",
        "amount": 19.7,
        "percent": 131,
        "kcal": 580,
        "frame": 5666
      },
      {
        "name": "Wheat germ",
        "amount": 16.0,
        "percent": 107,
        "kcal": 382,
        "frame": 2810
      },
      {
        "name": "Hazelnuts",
        "amount": 15.0,
        "percent": 100,
        "kcal": 628,
        "frame": 453
      },
      {
        "name": "Hummus, commercial",
        "amount": 15.0,
        "percent": 100,
        "kcal": 237,
        "frame": 7831
      },
      {
        "name": "Garlic bread, frozen",
        "amount": 13.7,
        "percent": 91,
        "kcal": 350,
        "frame": 2871
      },
      {
        "name": "Restaurant, family style, chicken fingers, from kid's menu",
        "amount": 13.6,
        "percent": 91,
        "kcal": 307,
        "frame": 14065
      },
      {
        "name": "Peppers, sweet, red, sauteed",
        "amount": 13.2,
        "percent": 88,
        "kcal": 133,
        "frame": 2512
      },
      {
        "name": "Fish, fish sticks, frozen, prepared",
        "amount": 13.1,
        "percent": 87,
        "kcal": 277,
        "frame": 10974
      }
    ]
  },
  "vitamin-k": {
    "unit": "µg",
    "dailyValue": 120,
    "foods": [
      {
        "name": "Amaranth leaves, raw",
        "amount": 1140.0,
        "percent": 950,
        "kcal": 23,
        "frame": 6850
      },
      {
        "name": "Chard, cooked",
        "amount": 866.0,
        "percent": 722,
        "kcal": 44,
        "frame": 10161
      },
      {
        "name": "Dandelion greens, cooked",
        "amount": 812.0,
        "percent": 677,
        "kcal": 71,
        "frame": 2510
      },
      {
        "name": "Native Lemongrass",
        "amount": 771.0,
        "percent": 642,
        "kcal": 99,
        "frame": 3389
      },
      {
        "name": "Lovage",
        "amount": 771.0,
        "percent": 642,
        "kcal": 28,
        "frame": 11635
      },
      {
        "name": "Hoja santa (Mexico)",
        "amount": 771.0,
        "percent": 642,
        "kcal": 40,
        "frame": 13093
      },
      {
        "name": "Tamarind leaf",
        "amount": 771.0,
        "percent": 642,
        "kcal": 50,
        "frame": 11718
      },
      {
        "name": "Licorice root",
        "amount": 771.0,
        "percent": 642,
        "kcal": 350,
        "frame": 13595
      },
      {
        "name": "Mustard greens, cooked, boiled, drained, without salt",
        "amount": 593.0,
        "percent": 494,
        "kcal": 26,
        "frame": 4187
      },
      {
        "name": "Spinach, fresh, cooked, no added fat",
        "amount": 566.0,
        "percent": 472,
        "kcal": 33,
        "frame": 5849
      },
      {
        "name": "Cress, cooked",
        "amount": 566.0,
        "percent": 472,
        "kcal": 58,
        "frame": 797
      },
      {
        "name": "Sorrel",
        "amount": 551.0,
        "percent": 459,
        "kcal": 21,
        "frame": 11432
      }
    ]
  },
  "thiamin": {
    "unit": "mg",
    "dailyValue": 1.2,
    "foods": [
      {
        "name": "Seeds, sesame flour, high-fat",
        "amount": 2.68,
        "percent": 224,
        "kcal": 526,
        "frame": 4031
      },
      {
        "name": "Wheat germ, crude",
        "amount": 1.88,
        "percent": 157,
        "kcal": 360,
        "frame": 6044
      },
      {
        "name": "Lamb, New Zealand, imported, liver, cooked, soaked and fried",
        "amount": 1.57,
        "percent": 131,
        "kcal": 168,
        "frame": 12349
      },
      {
        "name": "Nuts, macadamia nuts, raw",
        "amount": 1.2,
        "percent": 100,
        "kcal": 718,
        "frame": 10315
      },
      {
        "name": "Pork, fresh, shoulder, blade, boston (roasts), separable lean only, cooked, roasted",
        "amount": 1.12,
        "percent": 93,
        "kcal": 232,
        "frame": 3705
      },
      {
        "name": "Macaroni or noodles with cheese, microwaveable, unprepared",
        "amount": 1.04,
        "percent": 87,
        "kcal": 388,
        "frame": 5530
      },
      {
        "name": "Winged beans, mature seeds, raw",
        "amount": 1.03,
        "percent": 86,
        "kcal": 409,
        "frame": 4597
      },
      {
        "name": "Tahini",
        "amount": 0.993,
        "percent": 83,
        "kcal": 697,
        "frame": 9007
      },
      {
        "name": "Ham, canned",
        "amount": 0.961,
        "percent": 80,
        "kcal": 167,
        "frame": 6413
      },
      {
        "name": "Soybeans, mature seeds, raw",
        "amount": 0.874,
        "percent": 73,
        "kcal": 446,
        "frame": 2078
      },
      {
        "name": "Lentils, raw",
        "amount": 0.873,
        "percent": 73,
        "kcal": 352,
        "frame": 12204
      },
      {
        "name": "Pistachios",
        "amount": 0.87,
        "percent": 72,
        "kcal": 557,
        "frame": 13827
      }
    ]
  },
  "riboflavin": {
    "unit": "mg",
    "dailyValue": 1.3,
    "foods": [
      {
        "name": "Lamb, New Zealand, imported, liver, cooked, soaked and fried",
        "amount": 5.27,
        "percent": 405,
        "kcal": 168,
        "frame": 12349
      },
      {
        "name": "Beef, variety meats and by-products, kidneys, cooked, simmered",
        "amount": 2.97,
        "percent": 228,
        "kcal": 158,
        "frame": 5099
      },
      {
        "name": "Mollusks, cuttlefish, mixed species, cooked, moist heat",
        "amount": 1.73,
        "percent": 133,
        "kcal": 158,
        "frame": 1774
      },
      {
        "name": "Turkey, whole, giblets, cooked, simmered",
        "amount": 1.54,
        "percent": 119,
        "kcal": 173,
        "frame": 10875
      },
      {
        "name": "Liverwurst",
        "amount": 1.52,
        "percent": 117,
        "kcal": 327,
        "frame": 14052
      },
      {
        "name": "Canada Goose, breast meat only, skinless, raw",
        "amount": 1.52,
        "percent": 117,
        "kcal": 133,
        "frame": 7300
      },
      {
        "name": "Grapes, muscadine, raw",
        "amount": 1.5,
        "percent": 115,
        "kcal": 57,
        "frame": 7709
      },
      {
        "name": "Cheese, gjetost",
        "amount": 1.38,
        "percent": 106,
        "kcal": 466,
        "frame": 2809
      },
      {
        "name": "Almonds, NFS",
        "amount": 1.2,
        "percent": 92,
        "kcal": 598,
        "frame": 7425
      },
      {
        "name": "Soy flour, full-fat, raw",
        "amount": 1.16,
        "percent": 89,
        "kcal": 434,
        "frame": 3484
      },
      {
        "name": "Soybeans, mature seeds, raw",
        "amount": 0.87,
        "percent": 67,
        "kcal": 446,
        "frame": 2078
      },
      {
        "name": "Wheat germ",
        "amount": 0.82,
        "percent": 63,
        "kcal": 382,
        "frame": 2810
      }
    ]
  },
  "niacin": {
    "unit": "mg",
    "dailyValue": 16,
    "foods": [
      {
        "name": "Fish, tuna, cooked",
        "amount": 22.9,
        "percent": 143,
        "kcal": 176,
        "frame": 5248
      },
      {
        "name": "Beef, variety meats and by-products, liver, cooked, braised",
        "amount": 17.5,
        "percent": 110,
        "kcal": 191,
        "frame": 732
      },
      {
        "name": "Peanut butter, lower sugar",
        "amount": 16.4,
        "percent": 102,
        "kcal": 650,
        "frame": 10937
      },
      {
        "name": "Chicken, broilers or fryers, breast, meat only, cooked, fried",
        "amount": 14.8,
        "percent": 92,
        "kcal": 187,
        "frame": 8173
      },
      {
        "name": "Anchovies",
        "amount": 14.3,
        "percent": 89,
        "kcal": 210,
        "frame": 11632
      },
      {
        "name": "Seeds, sesame flour, high-fat",
        "amount": 13.4,
        "percent": 84,
        "kcal": 526,
        "frame": 4031
      },
      {
        "name": "Veal, leg (top round), separable lean only, cooked, pan-fried, not breaded",
        "amount": 12.6,
        "percent": 79,
        "kcal": 183,
        "frame": 6312
      },
      {
        "name": "Turkey, all classes, light meat, cooked, roasted",
        "amount": 11.8,
        "percent": 73,
        "kcal": 147,
        "frame": 5408
      },
      {
        "name": "Pork bacon, NS as to fresh, smoked or cured, reduced sodium, cooked",
        "amount": 11.1,
        "percent": 69,
        "kcal": 541,
        "frame": 1382
      },
      {
        "name": "Venison, steak",
        "amount": 10.7,
        "percent": 67,
        "kcal": 149,
        "frame": 8846
      },
      {
        "name": "Lamb, Australian, imported, fresh, tenderloin, boneless, separable lean only, trimmed to 1/8\" fat, cooked, roasted",
        "amount": 9.58,
        "percent": 60,
        "kcal": 184,
        "frame": 8165
      },
      {
        "name": "Fruit juice, acai blend",
        "amount": 9.06,
        "percent": 57,
        "kcal": 62,
        "frame": 14131
      }
    ]
  },
  "pantothenic-acid": {
    "unit": "mg",
    "dailyValue": 5,
    "foods": [
      {
        "name": "Beef, New Zealand, imported, variety meats and by-products, liver, raw",
        "amount": 10.3,
        "percent": 206,
        "kcal": 133,
        "frame": 7120
      },
      {
        "name": "Seeds, sunflower seed kernels, toasted, with salt added",
        "amount": 7.06,
        "percent": 141,
        "kcal": 619,
        "frame": 5634
      },
      {
        "name": "Chicken, broilers or fryers, giblets, cooked, fried",
        "amount": 4.45,
        "percent": 89,
        "kcal": 277,
        "frame": 13004
      },
      {
        "name": "Grape leaves, canned",
        "amount": 4.27,
        "percent": 85,
        "kcal": 69,
        "frame": 14469
      },
      {
        "name": "Mushrooms, shiitake, cooked, without salt",
        "amount": 3.59,
        "percent": 72,
        "kcal": 56,
        "frame": 10165
      },
      {
        "name": "Egg, yolk, raw, frozen, pasteurized",
        "amount": 3.44,
        "percent": 69,
        "kcal": 296,
        "frame": 12120
      },
      {
        "name": "Cheese, gjetost",
        "amount": 3.35,
        "percent": 67,
        "kcal": 466,
        "frame": 2809
      },
      {
        "name": "Mollusks, abalone, mixed species, raw",
        "amount": 3.0,
        "percent": 60,
        "kcal": 105,
        "frame": 3997
      },
      {
        "name": "Liverwurst spread",
        "amount": 2.95,
        "percent": 59,
        "kcal": 305,
        "frame": 1292
      },
      {
        "name": "Cornmeal, white (Navajo)",
        "amount": 2.49,
        "percent": 50,
        "kcal": 398,
        "frame": 13946
      },
      {
        "name": "Wheat germ, crude",
        "amount": 2.26,
        "percent": 45,
        "kcal": 360,
        "frame": 6044
      },
      {
        "name": "Lentils, raw",
        "amount": 2.14,
        "percent": 43,
        "kcal": 352,
        "frame": 12204
      }
    ]
  },
  "vitamin-b6": {
    "unit": "mg",
    "dailyValue": 1.7,
    "foods": [
      {
        "name": "Nuts, pistachio nuts, raw",
        "amount": 1.7,
        "percent": 100,
        "kcal": 560,
        "frame": 2148
      },
      {
        "name": "Wheat germ, crude",
        "amount": 1.3,
        "percent": 76,
        "kcal": 360,
        "frame": 6044
      },
      {
        "name": "Garlic, raw",
        "amount": 1.24,
        "percent": 73,
        "kcal": 149,
        "frame": 6224
      },
      {
        "name": "Drumstick leaves, raw",
        "amount": 1.2,
        "percent": 71,
        "kcal": 64,
        "frame": 12665
      },
      {
        "name": "Chicken, broiler or fryers, breast, skinless, boneless, meat only, cooked, grilled",
        "amount": 1.16,
        "percent": 68,
        "kcal": 151,
        "frame": 1066
      },
      {
        "name": "Fruit juice, acai blend",
        "amount": 1.1,
        "percent": 65,
        "kcal": 62,
        "frame": 14131
      },
      {
        "name": "Beef, variety meats and by-products, liver, raw",
        "amount": 1.08,
        "percent": 64,
        "kcal": 135,
        "frame": 1340
      },
      {
        "name": "Turkey, ground, fat free, pan-broiled crumbles",
        "amount": 1.08,
        "percent": 64,
        "kcal": 151,
        "frame": 186
      },
      {
        "name": "Fish, tuna, cooked",
        "amount": 1.07,
        "percent": 63,
        "kcal": 176,
        "frame": 5248
      },
      {
        "name": "Soy flour, low-fat",
        "amount": 1.05,
        "percent": 62,
        "kcal": 372,
        "frame": 3304
      },
      {
        "name": "Seeds, sesame butter, paste",
        "amount": 0.816,
        "percent": 48,
        "kcal": 586,
        "frame": 1297
      },
      {
        "name": "Hearts of palm, raw",
        "amount": 0.81,
        "percent": 48,
        "kcal": 115,
        "frame": 6225
      }
    ]
  },
  "vitamin-b12": {
    "unit": "µg",
    "dailyValue": 2.4,
    "foods": [
      {
        "name": "Veal, variety meats and by-products, liver, raw",
        "amount": 59.9,
        "percent": 2494,
        "kcal": 140,
        "frame": 7968
      },
      {
        "name": "Lamb, New Zealand, imported, kidney, cooked, soaked and fried",
        "amount": 55.6,
        "percent": 2315,
        "kcal": 112,
        "frame": 4304
      },
      {
        "name": "Mollusks, clam, mixed species, cooked, breaded and fried",
        "amount": 40.3,
        "percent": 1678,
        "kcal": 202,
        "frame": 666
      },
      {
        "name": "Oysters, canned",
        "amount": 20.8,
        "percent": 866,
        "kcal": 74,
        "frame": 12742
      },
      {
        "name": "Liverwurst",
        "amount": 20.1,
        "percent": 837,
        "kcal": 327,
        "frame": 14052
      },
      {
        "name": "Fish, herring, Atlantic, kippered",
        "amount": 18.7,
        "percent": 779,
        "kcal": 217,
        "frame": 39
      },
      {
        "name": "Turkey, whole, giblets, cooked, simmered",
        "amount": 15.9,
        "percent": 662,
        "kcal": 173,
        "frame": 10875
      },
      {
        "name": "Octopus",
        "amount": 12.9,
        "percent": 540,
        "kcal": 226,
        "frame": 10850
      },
      {
        "name": "Mussels",
        "amount": 12.9,
        "percent": 538,
        "kcal": 109,
        "frame": 6469
      },
      {
        "name": "Crustaceans, crab, alaska king, cooked, moist heat",
        "amount": 11.5,
        "percent": 479,
        "kcal": 97,
        "frame": 956
      },
      {
        "name": "Beef, plate steak, boneless, outside skirt, separable lean only, trimmed to 0\" fat, choice, cooked, grilled",
        "amount": 8.18,
        "percent": 341,
        "kcal": 291,
        "frame": 5594
      },
      {
        "name": "Seafood sauce",
        "amount": 8.08,
        "percent": 337,
        "kcal": 203,
        "frame": 12173
      }
    ]
  },
  "folate": {
    "unit": "µg",
    "dailyValue": 400,
    "foods": [
      {
        "name": "Goose, liver, raw",
        "amount": 738.0,
        "percent": 184,
        "kcal": 133,
        "frame": 2812
      },
      {
        "name": "Chickpeas (garbanzo beans, bengal gram), mature seeds, raw",
        "amount": 557.0,
        "percent": 139,
        "kcal": 378,
        "frame": 2262
      },
      {
        "name": "Lentils, raw",
        "amount": 479.0,
        "percent": 120,
        "kcal": 352,
        "frame": 12204
      },
      {
        "name": "Chicken, capons, giblets, cooked, simmered",
        "amount": 414.0,
        "percent": 103,
        "kcal": 164,
        "frame": 3100
      },
      {
        "name": "Rice, white, short-grain, enriched, uncooked",
        "amount": 389.0,
        "percent": 97,
        "kcal": 358,
        "frame": 8634
      },
      {
        "name": "Cornmeal, white, self-rising, degermed, enriched",
        "amount": 375.0,
        "percent": 94,
        "kcal": 355,
        "frame": 14419
      },
      {
        "name": "Soybeans, mature seeds, raw",
        "amount": 375.0,
        "percent": 94,
        "kcal": 446,
        "frame": 2078
      },
      {
        "name": "Lupins, mature seeds, raw",
        "amount": 355.0,
        "percent": 89,
        "kcal": 371,
        "frame": 13398
      },
      {
        "name": "Wheat germ",
        "amount": 352.0,
        "percent": 88,
        "kcal": 382,
        "frame": 2810
      },
      {
        "name": "Soy flour, full-fat, raw",
        "amount": 345.0,
        "percent": 86,
        "kcal": 434,
        "frame": 3484
      },
      {
        "name": "Arrowroot, raw",
        "amount": 338.0,
        "percent": 84,
        "kcal": 65,
        "frame": 13367
      },
      {
        "name": "Macaroni or noodles with cheese, microwaveable, unprepared",
        "amount": 334.0,
        "percent": 84,
        "kcal": 388,
        "frame": 5530
      }
    ]
  },
  "choline": {
    "unit": "mg",
    "dailyValue": 550,
    "foods": [
      {
        "name": "Egg, yolk only, raw",
        "amount": 820.0,
        "percent": 149,
        "kcal": 328,
        "frame": 12269
      },
      {
        "name": "Beef, variety meats and by-products, kidneys, cooked, simmered",
        "amount": 513.0,
        "percent": 93,
        "kcal": 158,
        "frame": 5099
      },
      {
        "name": "Chicken, liver, all classes, cooked, pan-fried",
        "amount": 327.0,
        "percent": 59,
        "kcal": 172,
        "frame": 4340
      },
      {
        "name": "Liverwurst",
        "amount": 256.0,
        "percent": 47,
        "kcal": 327,
        "frame": 14052
      },
      {
        "name": "Soy flour, low-fat",
        "amount": 192.0,
        "percent": 35,
        "kcal": 372,
        "frame": 3304
      },
      {
        "name": "Wheat germ",
        "amount": 179.0,
        "percent": 32,
        "kcal": 382,
        "frame": 2810
      },
      {
        "name": "Turkey, whole, giblets, raw",
        "amount": 160.0,
        "percent": 29,
        "kcal": 124,
        "frame": 11472
      },
      {
        "name": "Veal, leg, top round, cap off, cutlet, boneless, cooked, grilled",
        "amount": 160.0,
        "percent": 29,
        "kcal": 151,
        "frame": 707
      },
      {
        "name": "Peas, green, split, mature seeds, raw",
        "amount": 157.0,
        "percent": 29,
        "kcal": 364,
        "frame": 10289
      },
      {
        "name": "Pork jerky",
        "amount": 143.0,
        "percent": 26,
        "kcal": 412,
        "frame": 7462
      },
      {
        "name": "Crustaceans, shrimp, mixed species, cooked, moist heat (may contain additives to retain moisture)",
        "amount": 135.0,
        "percent": 25,
        "kcal": 119,
        "frame": 8278
      },
      {
        "name": "Bacon bits",
        "amount": 135.0,
        "percent": 25,
        "kcal": 476,
        "frame": 2126
      }
    ]
  },
  "calcium": {
    "unit": "mg",
    "dailyValue": 1300,
    "foods": [
      {
        "name": "Poppy Seeds",
        "amount": 1440.0,
        "percent": 111,
        "kcal": 525,
        "frame": 12318
      },
      {
        "name": "Toasted sesame seed",
        "amount": 1260.0,
        "percent": 97,
        "kcal": 615,
        "frame": 11802
      },
      {
        "name": "Cheese, parmesan, shredded",
        "amount": 1250.0,
        "percent": 96,
        "kcal": 415,
        "frame": 5361
      },
      {
        "name": "Tofu, salted and fermented (fuyu), prepared with calcium sulfate",
        "amount": 1230.0,
        "percent": 95,
        "kcal": 116,
        "frame": 9136
      },
      {
        "name": "Bread, whole grain white, toasted",
        "amount": 752.0,
        "percent": 58,
        "kcal": 262,
        "frame": 10288
      },
      {
        "name": "Queso cotija",
        "amount": 700.0,
        "percent": 54,
        "kcal": 351,
        "frame": 12741
      },
      {
        "name": "Chia seeds",
        "amount": 631.0,
        "percent": 49,
        "kcal": 486,
        "frame": 9339
      },
      {
        "name": "Stinging Nettles, blanched (Northern Plains Indians)",
        "amount": 481.0,
        "percent": 37,
        "kcal": 42,
        "frame": 1018
      },
      {
        "name": "Agave, cooked (Southwest)",
        "amount": 460.0,
        "percent": 35,
        "kcal": 135,
        "frame": 129
      },
      {
        "name": "Winged beans, mature seeds, raw",
        "amount": 440.0,
        "percent": 34,
        "kcal": 409,
        "frame": 4597
      },
      {
        "name": "Fireweed, leaves, raw",
        "amount": 429.0,
        "percent": 33,
        "kcal": 103,
        "frame": 13782
      },
      {
        "name": "Fish, sardines, canned",
        "amount": 382.0,
        "percent": 29,
        "kcal": 208,
        "frame": 5793
      }
    ]
  },
  "iron": {
    "unit": "mg",
    "dailyValue": 18,
    "foods": [
      {
        "name": "Beef, variety meats and by-products, spleen, raw",
        "amount": 44.5,
        "percent": 247,
        "kcal": 105,
        "frame": 3029
      },
      {
        "name": "Goose, liver, raw",
        "amount": 30.5,
        "percent": 170,
        "kcal": 133,
        "frame": 2812
      },
      {
        "name": "Seeds, sesame butter, paste",
        "amount": 19.2,
        "percent": 107,
        "kcal": 586,
        "frame": 1297
      },
      {
        "name": "Baking chocolate, unsweetened, squares",
        "amount": 17.4,
        "percent": 97,
        "kcal": 642,
        "frame": 13118
      },
      {
        "name": "Soybeans, mature seeds, raw",
        "amount": 15.7,
        "percent": 87,
        "kcal": 446,
        "frame": 2078
      },
      {
        "name": "Lamb, New Zealand, imported, kidney, cooked, soaked and fried",
        "amount": 14.7,
        "percent": 82,
        "kcal": 112,
        "frame": 4304
      },
      {
        "name": "Mollusks, clam, mixed species, cooked, breaded and fried",
        "amount": 13.9,
        "percent": 77,
        "kcal": 202,
        "frame": 666
      },
      {
        "name": "Winged beans, mature seeds, raw",
        "amount": 13.4,
        "percent": 75,
        "kcal": 409,
        "frame": 4597
      },
      {
        "name": "Garden cress seed",
        "amount": 13.0,
        "percent": 72,
        "kcal": 454,
        "frame": 8221
      },
      {
        "name": "Mushrooms, morel, raw",
        "amount": 12.2,
        "percent": 68,
        "kcal": 31,
        "frame": 9098
      },
      {
        "name": "Liverwurst",
        "amount": 11.2,
        "percent": 62,
        "kcal": 327,
        "frame": 14052
      },
      {
        "name": "Chicken, broilers or fryers, giblets, cooked, fried",
        "amount": 10.3,
        "percent": 57,
        "kcal": 277,
        "frame": 13004
      }
    ]
  },
  "magnesium": {
    "unit": "mg",
    "dailyValue": 420,
    "foods": [
      {
        "name": "Seeds, hemp seed, hulled",
        "amount": 700.0,
        "percent": 167,
        "kcal": 553,
        "frame": 12570
      },
      {
        "name": "Pumpkin seeds, NFS",
        "amount": 550.0,
        "percent": 131,
        "kcal": 574,
        "frame": 11716
      },
      {
        "name": "Soy flour, full-fat, raw",
        "amount": 429.0,
        "percent": 102,
        "kcal": 434,
        "frame": 3484
      },
      {
        "name": "Brazil nuts",
        "amount": 376.0,
        "percent": 90,
        "kcal": 659,
        "frame": 11584
      },
      {
        "name": "Flax seeds",
        "amount": 372.0,
        "percent": 89,
        "kcal": 545,
        "frame": 10709
      },
      {
        "name": "Garden cress seed",
        "amount": 370.0,
        "percent": 88,
        "kcal": 454,
        "frame": 8221
      },
      {
        "name": "Tahini",
        "amount": 357.0,
        "percent": 85,
        "kcal": 697,
        "frame": 9007
      },
      {
        "name": "White sesame",
        "amount": 351.0,
        "percent": 84,
        "kcal": 573,
        "frame": 12918
      },
      {
        "name": "Poppy Seeds",
        "amount": 347.0,
        "percent": 83,
        "kcal": 525,
        "frame": 12318
      },
      {
        "name": "Chia seeds",
        "amount": 335.0,
        "percent": 80,
        "kcal": 486,
        "frame": 9339
      },
      {
        "name": "Baking chocolate, unsweetened, squares",
        "amount": 327.0,
        "percent": 78,
        "kcal": 642,
        "frame": 13118
      },
      {
        "name": "Wheat germ",
        "amount": 320.0,
        "percent": 76,
        "kcal": 382,
        "frame": 2810
      }
    ]
  },
  "phosphorus": {
    "unit": "mg",
    "dailyValue": 1250,
    "foods": [
      {
        "name": "Seeds, hemp seed, hulled",
        "amount": 1650.0,
        "percent": 132,
        "kcal": 553,
        "frame": 12570
      },
      {
        "name": "Pumpkin seeds, NFS",
        "amount": 1170.0,
        "percent": 94,
        "kcal": 574,
        "frame": 11716
      },
      {
        "name": "Mixed seeds",
        "amount": 1160.0,
        "percent": 93,
        "kcal": 580,
        "frame": 5666
      },
      {
        "name": "Sunflower seeds, plain, unsalted",
        "amount": 1160.0,
        "percent": 92,
        "kcal": 582,
        "frame": 6167
      },
      {
        "name": "Wheat germ",
        "amount": 1150.0,
        "percent": 92,
        "kcal": 382,
        "frame": 2810
      },
      {
        "name": "Melon Seeds (egusi)",
        "amount": 940.0,
        "percent": 75,
        "kcal": 590,
        "frame": 3
      },
      {
        "name": "Poppy Seeds",
        "amount": 870.0,
        "percent": 70,
        "kcal": 525,
        "frame": 12318
      },
      {
        "name": "Chia seeds",
        "amount": 860.0,
        "percent": 69,
        "kcal": 486,
        "frame": 9339
      },
      {
        "name": "Black mustard",
        "amount": 841.0,
        "percent": 67,
        "kcal": 508,
        "frame": 6058
      },
      {
        "name": "Cheese, American, reduced fat",
        "amount": 829.0,
        "percent": 66,
        "kcal": 240,
        "frame": 4749
      },
      {
        "name": "Brazil nuts",
        "amount": 725.0,
        "percent": 58,
        "kcal": 659,
        "frame": 11584
      },
      {
        "name": "Tahini",
        "amount": 719.0,
        "percent": 58,
        "kcal": 697,
        "frame": 9007
      }
    ]
  },
  "potassium": {
    "unit": "mg",
    "dailyValue": 4700,
    "foods": [
      {
        "name": "Soy flour, full-fat, raw",
        "amount": 2520.0,
        "percent": 54,
        "kcal": 434,
        "frame": 3484
      },
      {
        "name": "Hearts of palm, raw",
        "amount": 1810.0,
        "percent": 38,
        "kcal": 115,
        "frame": 6225
      },
      {
        "name": "Soybeans, mature seeds, raw",
        "amount": 1800.0,
        "percent": 38,
        "kcal": 446,
        "frame": 2078
      },
      {
        "name": "Molasses",
        "amount": 1460.0,
        "percent": 31,
        "kcal": 290,
        "frame": 10944
      },
      {
        "name": "Cheese, gjetost",
        "amount": 1410.0,
        "percent": 30,
        "kcal": 466,
        "frame": 2809
      },
      {
        "name": "Garden cress seed",
        "amount": 1400.0,
        "percent": 30,
        "kcal": 454,
        "frame": 8221
      },
      {
        "name": "Salami, pork, beef, less sodium",
        "amount": 1370.0,
        "percent": 29,
        "kcal": 396,
        "frame": 6561
      },
      {
        "name": "Lambsquarters, raw (Northern Plains Indians)",
        "amount": 1270.0,
        "percent": 27,
        "kcal": 47,
        "frame": 13778
      },
      {
        "name": "Potato sticks, plain",
        "amount": 1240.0,
        "percent": 26,
        "kcal": 522,
        "frame": 1124
      },
      {
        "name": "Seeds, hemp seed, hulled",
        "amount": 1200.0,
        "percent": 26,
        "kcal": 553,
        "frame": 12570
      },
      {
        "name": "Baking chocolate, unsweetened, liquid",
        "amount": 1170.0,
        "percent": 25,
        "kcal": 472,
        "frame": 13655
      },
      {
        "name": "Apricot, dried",
        "amount": 1160.0,
        "percent": 25,
        "kcal": 241,
        "frame": 6244
      }
    ]
  },
  "zinc": {
    "unit": "mg",
    "dailyValue": 11,
    "foods": [
      {
        "name": "Oysters, canned",
        "amount": 98.9,
        "percent": 899,
        "kcal": 74,
        "frame": 12742
      },
      {
        "name": "Wheat germ",
        "amount": 16.7,
        "percent": 152,
        "kcal": 382,
        "frame": 2810
      },
      {
        "name": "Beef, chuck, short ribs, boneless, separable lean only, trimmed to 0\" fat, select, cooked, braised",
        "amount": 12.3,
        "percent": 112,
        "kcal": 224,
        "frame": 6017
      },
      {
        "name": "Veal, variety meats and by-products, liver, raw",
        "amount": 12.0,
        "percent": 109,
        "kcal": 140,
        "frame": 7968
      },
      {
        "name": "Seeds, sesame flour, partially defatted",
        "amount": 10.7,
        "percent": 97,
        "kcal": 382,
        "frame": 8719
      },
      {
        "name": "Baking chocolate, unsweetened, squares",
        "amount": 9.63,
        "percent": 88,
        "kcal": 642,
        "frame": 13118
      },
      {
        "name": "Lamb, foreshank, separable lean only, trimmed to 1/4\" fat, choice, cooked, braised",
        "amount": 8.66,
        "percent": 79,
        "kcal": 187,
        "frame": 8324
      },
      {
        "name": "Poppy Seeds (Posto)",
        "amount": 8.0,
        "percent": 73,
        "kcal": 525,
        "frame": 4317
      },
      {
        "name": "Pumpkin seeds, NFS",
        "amount": 7.64,
        "percent": 69,
        "kcal": 574,
        "frame": 11716
      },
      {
        "name": "Crustaceans, crab, alaska king, cooked, moist heat",
        "amount": 7.62,
        "percent": 69,
        "kcal": 97,
        "frame": 956
      },
      {
        "name": "Melon Seeds (egusi)",
        "amount": 7.2,
        "percent": 65,
        "kcal": 590,
        "frame": 3
      },
      {
        "name": "Pork jerky",
        "amount": 6.76,
        "percent": 61,
        "kcal": 412,
        "frame": 7462
      }
    ]
  },
  "copper": {
    "unit": "mg",
    "dailyValue": 0.9,
    "foods": [
      {
        "name": "Veal, variety meats and by-products, liver, cooked, pan-fried",
        "amount": 15.1,
        "percent": 1672,
        "kcal": 193,
        "frame": 922
      },
      {
        "name": "Mollusks, oyster, eastern, wild, cooked, moist heat",
        "amount": 5.71,
        "percent": 634,
        "kcal": 102,
        "frame": 8911
      },
      {
        "name": "Seeds, sesame butter, paste",
        "amount": 4.21,
        "percent": 468,
        "kcal": 586,
        "frame": 1297
      },
      {
        "name": "Baking chocolate, unsweetened, squares",
        "amount": 3.23,
        "percent": 359,
        "kcal": 642,
        "frame": 13118
      },
      {
        "name": "Soy flour, full-fat, raw",
        "amount": 2.92,
        "percent": 324,
        "kcal": 434,
        "frame": 3484
      },
      {
        "name": "Winged beans, mature seeds, raw",
        "amount": 2.88,
        "percent": 320,
        "kcal": 409,
        "frame": 4597
      },
      {
        "name": "Calamari, cooked",
        "amount": 2.35,
        "percent": 261,
        "kcal": 155,
        "frame": 9496
      },
      {
        "name": "Cashews, NFS",
        "amount": 2.22,
        "percent": 247,
        "kcal": 574,
        "frame": 7387
      },
      {
        "name": "Grape leaves, canned",
        "amount": 1.84,
        "percent": 205,
        "kcal": 69,
        "frame": 14469
      },
      {
        "name": "Sunflower seeds, plain, unsalted",
        "amount": 1.83,
        "percent": 203,
        "kcal": 582,
        "frame": 6167
      },
      {
        "name": "Brazil nuts",
        "amount": 1.74,
        "percent": 194,
        "kcal": 659,
        "frame": 11584
      },
      {
        "name": "Hazelnuts",
        "amount": 1.73,
        "percent": 192,
        "kcal": 628,
        "frame": 453
      }
    ]
  },
  "manganese": {
    "unit": "mg",
    "dailyValue": 2.3,
    "foods": [
      {
        "name": "Wheat germ, crude",
        "amount": 13.3,
        "percent": 578,
        "kcal": 360,
        "frame": 6044
      },
      {
        "name": "Nuts, hazelnuts or filberts, blanched",
        "amount": 12.7,
        "percent": 550,
        "kcal": 629,
        "frame": 6790
      },
      {
        "name": "Teff, uncooked",
        "amount": 9.24,
        "percent": 402,
        "kcal": 367,
        "frame": 2732
      },
      {
        "name": "Seeds, hemp seed, hulled",
        "amount": 7.6,
        "percent": 330,
        "kcal": 553,
        "frame": 12570
      },
      {
        "name": "Mollusks, mussel, blue, cooked, moist heat",
        "amount": 6.8,
        "percent": 296,
        "kcal": 172,
        "frame": 5134
      },
      {
        "name": "Fireweed, leaves, raw",
        "amount": 6.7,
        "percent": 291,
        "kcal": 103,
        "frame": 13782
      },
      {
        "name": "Poppy Seeds",
        "amount": 6.7,
        "percent": 291,
        "kcal": 525,
        "frame": 12318
      },
      {
        "name": "Lemon grass (citronella), raw",
        "amount": 5.22,
        "percent": 227,
        "kcal": 99,
        "frame": 9561
      },
      {
        "name": "Oats",
        "amount": 4.92,
        "percent": 214,
        "kcal": 389,
        "frame": 12850
      },
      {
        "name": "Sugars, maple",
        "amount": 4.42,
        "percent": 192,
        "kcal": 354,
        "frame": 384
      },
      {
        "name": "Peanut flour, low fat",
        "amount": 4.23,
        "percent": 184,
        "kcal": 428,
        "frame": 10729
      },
      {
        "name": "Baking chocolate, unsweetened, squares",
        "amount": 4.17,
        "percent": 181,
        "kcal": 642,
        "frame": 13118
      }
    ]
  },
  "selenium": {
    "unit": "µg",
    "dailyValue": 55,
    "foods": [
      {
        "name": "Pork, fresh, variety meats and by-products, kidneys, cooked, braised",
        "amount": 312.0,
        "percent": 566,
        "kcal": 151,
        "frame": 5085
      },
      {
        "name": "Black mustard",
        "amount": 164.0,
        "percent": 298,
        "kcal": 508,
        "frame": 6058
      },
      {
        "name": "Mollusks, oyster, Pacific, cooked, moist heat",
        "amount": 154.0,
        "percent": 280,
        "kcal": 163,
        "frame": 5056
      },
      {
        "name": "Mixed nuts, unroasted",
        "amount": 147.0,
        "percent": 267,
        "kcal": 616,
        "frame": 5978
      },
      {
        "name": "Turkey, young hen, skin only, cooked, roasted",
        "amount": 144.0,
        "percent": 262,
        "kcal": 482,
        "frame": 7771
      },
      {
        "name": "Flax seeds",
        "amount": 136.0,
        "percent": 247,
        "kcal": 545,
        "frame": 10709
      },
      {
        "name": "Fish, tuna, cooked",
        "amount": 112.0,
        "percent": 205,
        "kcal": 176,
        "frame": 5248
      },
      {
        "name": "Seeds, sunflower seed butter, with salt added",
        "amount": 104.0,
        "percent": 190,
        "kcal": 617,
        "frame": 7443
      },
      {
        "name": "Chicken, broilers or fryers, giblets, cooked, fried",
        "amount": 104.0,
        "percent": 189,
        "kcal": 277,
        "frame": 13004
      },
      {
        "name": "Semolina, enriched",
        "amount": 89.4,
        "percent": 163,
        "kcal": 360,
        "frame": 4738
      },
      {
        "name": "Lobster",
        "amount": 80.5,
        "percent": 146,
        "kcal": 97,
        "frame": 9932
      },
      {
        "name": "Wheat germ, crude",
        "amount": 79.2,
        "percent": 144,
        "kcal": 360,
        "frame": 6044
      }
    ]
  },
  "protein": {
    "unit": "g",
    "dailyValue": 50,
    "foods": [
      {
        "name": "Soy flour, low-fat",
        "amount": 49.8,
        "percent": 100,
        "kcal": 372,
        "frame": 3304
      },
      {
        "name": "Cheese, parmesan, low sodium",
        "amount": 41.6,
        "percent": 83,
        "kcal": 451,
        "frame": 6761
      },
      {
        "name": "Pork, cured, bacon, cooked, microwaved",
        "amount": 39.0,
        "percent": 78,
        "kcal": 476,
        "frame": 14184
      },
      {
        "name": "Soybeans, mature seeds, roasted, salted",
        "amount": 38.5,
        "percent": 77,
        "kcal": 469,
        "frame": 6052
      },
      {
        "name": "Veal, leg (top round), separable lean only, cooked, braised",
        "amount": 36.7,
        "percent": 73,
        "kcal": 203,
        "frame": 7731
      },
      {
        "name": "Lupins, mature seeds, raw",
        "amount": 36.2,
        "percent": 72,
        "kcal": 371,
        "frame": 13398
      },
      {
        "name": "Lamb, shoulder, arm, separable lean only, trimmed to 1/4\" fat, choice, cooked, braised",
        "amount": 35.5,
        "percent": 71,
        "kcal": 279,
        "frame": 4298
      },
      {
        "name": "Beef, New Zealand, imported, brisket point end, separable lean only, cooked, braised",
        "amount": 34.5,
        "percent": 69,
        "kcal": 202,
        "frame": 6779
      },
      {
        "name": "Chicken, broilers or fryers, breast, meat only, cooked, fried",
        "amount": 33.4,
        "percent": 67,
        "kcal": 187,
        "frame": 8173
      },
      {
        "name": "Mutton, cooked, roasted (Navajo)",
        "amount": 33.4,
        "percent": 67,
        "kcal": 234,
        "frame": 7033
      },
      {
        "name": "Mollusks, cuttlefish, mixed species, cooked, moist heat",
        "amount": 32.5,
        "percent": 65,
        "kcal": 158,
        "frame": 1774
      },
      {
        "name": "Pheasant, cooked, total edible",
        "amount": 32.4,
        "percent": 65,
        "kcal": 239,
        "frame": 7192
      }
    ]
  },
  "fibre": {
    "unit": "g",
    "dailyValue": 28,
    "foods": [
      {
        "name": "Pinon Nuts, roasted (Navajo)",
        "amount": 43.4,
        "percent": 155,
        "kcal": 541,
        "frame": 389
      },
      {
        "name": "Chia seeds",
        "amount": 34.4,
        "percent": 123,
        "kcal": 486,
        "frame": 9339
      },
      {
        "name": "Seeds, flaxseed",
        "amount": 27.3,
        "percent": 98,
        "kcal": 534,
        "frame": 6172
      },
      {
        "name": "Winged beans, mature seeds, raw",
        "amount": 25.9,
        "percent": 92,
        "kcal": 409,
        "frame": 4597
      },
      {
        "name": "Rose Hips, wild (Northern Plains Indians)",
        "amount": 24.1,
        "percent": 86,
        "kcal": 162,
        "frame": 6198
      },
      {
        "name": "Flax seeds",
        "amount": 23.1,
        "percent": 82,
        "kcal": 545,
        "frame": 10709
      },
      {
        "name": "Peas, green, split, mature seeds, raw",
        "amount": 22.2,
        "percent": 79,
        "kcal": 364,
        "frame": 10289
      },
      {
        "name": "Poppy Seeds",
        "amount": 19.5,
        "percent": 70,
        "kcal": 525,
        "frame": 12318
      },
      {
        "name": "Lupins, mature seeds, raw",
        "amount": 18.9,
        "percent": 68,
        "kcal": 371,
        "frame": 13398
      },
      {
        "name": "Papad, grilled or broiled",
        "amount": 18.6,
        "percent": 66,
        "kcal": 371,
        "frame": 361
      },
      {
        "name": "Baking chocolate, unsweetened, liquid",
        "amount": 18.1,
        "percent": 65,
        "kcal": 472,
        "frame": 13655
      },
      {
        "name": "Soybeans, mature seeds, roasted, salted",
        "amount": 17.7,
        "percent": 63,
        "kcal": 469,
        "frame": 6052
      }
    ]
  }
};
