import { FoodNames } from '../food-names';

/**
 * The foods that appear on the eight core articles, in every language.
 *
 * Those eight — magnesium, iron, calcium, zinc, vitamin D, B12, folate and
 * protein — are the ones every locale has, so these names are the ones every
 * locale needs. See ./rest.ts for the foods that only reach the English and
 * German pages.
 */
export const CORE_FOOD_NAMES: FoodNames = {
  /* ------------------------------------------------------------ seeds ── */
  'Seeds, hemp seed, hulled': {
    en: 'Hemp seeds, hulled',
    de: 'Hanfsamen, geschält',
    es: 'Semillas de cáñamo peladas',
    fr: 'Graines de chanvre décortiquées',
    it: 'Semi di canapa decorticati',
    da: 'Hampefrø, afskallede',
    bg: 'Конопено семе, обелено',
  },
  'Pumpkin seeds, NFS': {
    en: 'Pumpkin seeds',
    de: 'Kürbiskerne',
    es: 'Pipas de calabaza',
    fr: 'Graines de courge',
    it: 'Semi di zucca',
    da: 'Græskarkerner',
    bg: 'Тиквено семе',
  },
  'Flax seeds': {
    en: 'Flax seeds',
    de: 'Leinsamen',
    es: 'Semillas de lino',
    fr: 'Graines de lin',
    it: 'Semi di lino',
    da: 'Hørfrø',
    bg: 'Ленено семе',
  },
  'Chia seeds': {
    en: 'Chia seeds',
    de: 'Chiasamen',
    es: 'Semillas de chía',
    fr: 'Graines de chia',
    it: 'Semi di chia',
    da: 'Chiafrø',
    bg: 'Семена чиа',
  },
  'Poppy Seeds': {
    en: 'Poppy seeds',
    de: 'Mohnsamen',
    es: 'Semillas de amapola',
    fr: 'Graines de pavot',
    it: 'Semi di papavero',
    da: 'Birkes',
    bg: 'Маково семе',
  },
  'Poppy Seeds (Posto)': {
    en: 'Poppy seeds',
    de: 'Mohnsamen',
    es: 'Semillas de amapola',
    fr: 'Graines de pavot',
    it: 'Semi di papavero',
    da: 'Birkes',
    bg: 'Маково семе',
  },
  'Garden cress seed': {
    en: 'Garden cress seed',
    de: 'Gartenkressesamen',
    es: 'Semillas de mastuerzo',
    fr: 'Graines de cresson alénois',
    it: 'Semi di crescione',
    da: 'Karsefrø',
    bg: 'Семе от градинска кресон',
  },
  'Melon Seeds (egusi)': {
    en: 'Melon seeds (egusi)',
    de: 'Melonenkerne (Egusi)',
    es: 'Semillas de melón (egusi)',
    fr: 'Graines de melon (egusi)',
    it: 'Semi di melone (egusi)',
    da: 'Melonkerner (egusi)',
    bg: 'Семе от пъпеш (егуси)',
  },
  'Toasted sesame seed': {
    en: 'Sesame seeds, toasted',
    de: 'Sesamsamen, geröstet',
    es: 'Semillas de sésamo tostadas',
    fr: 'Graines de sésame grillées',
    it: 'Semi di sesamo tostati',
    da: 'Ristede sesamfrø',
    bg: 'Печен сусам',
  },
  'White sesame': {
    en: 'White sesame seeds',
    de: 'Weißer Sesam',
    es: 'Sésamo blanco',
    fr: 'Sésame blanc',
    it: 'Sesamo bianco',
    da: 'Hvid sesam',
    bg: 'Бял сусам',
  },
  'Seeds, sesame butter, paste': {
    en: 'Sesame paste',
    de: 'Sesammus',
    es: 'Pasta de sésamo',
    fr: 'Purée de sésame',
    it: 'Crema di sesamo',
    da: 'Sesampasta',
    bg: 'Сусамов тахан',
  },
  Tahini: {
    en: 'Tahini',
    de: 'Tahini',
    es: 'Tahini',
    fr: 'Tahini',
    it: 'Tahina',
    da: 'Tahin',
    bg: 'Тахан',
  },
  'Seeds, sesame flour, partially defatted': {
    en: 'Sesame flour, partly defatted',
    de: 'Sesammehl, teilentölt',
    es: 'Harina de sésamo parcialmente desgrasada',
    fr: 'Farine de sésame partiellement déshuilée',
    it: 'Farina di sesamo parzialmente sgrassata',
    da: 'Sesammel, delvist affedtet',
    bg: 'Сусамово брашно, частично обезмаслено',
  },

  /* ------------------------------------------------------------- nuts ── */
  'Brazil nuts': {
    en: 'Brazil nuts',
    de: 'Paranüsse',
    es: 'Nueces de Brasil',
    fr: 'Noix du Brésil',
    it: 'Noci del Brasile',
    da: 'Paranødder',
    bg: 'Бразилски орехи',
  },

  /* ---------------------------------------------------------- legumes ── */
  'Lentils, raw': {
    en: 'Lentils, dry',
    de: 'Linsen, trocken',
    es: 'Lentejas secas',
    fr: 'Lentilles sèches',
    it: 'Lenticchie secche',
    da: 'Linser, tørrede',
    bg: 'Леща, суха',
  },
  'Chickpeas (garbanzo beans, bengal gram), mature seeds, raw': {
    en: 'Chickpeas, dry',
    de: 'Kichererbsen, trocken',
    es: 'Garbanzos secos',
    fr: 'Pois chiches secs',
    it: 'Ceci secchi',
    da: 'Kikærter, tørrede',
    bg: 'Нахут, сух',
  },
  'Soybeans, mature seeds, raw': {
    en: 'Soybeans, dry',
    de: 'Sojabohnen, trocken',
    es: 'Semillas de soja secas',
    fr: 'Graines de soja sèches',
    it: 'Semi di soia secchi',
    da: 'Sojabønner, tørrede',
    bg: 'Соя, суха',
  },
  'Soybeans, mature seeds, roasted, salted': {
    en: 'Soybeans, roasted and salted',
    de: 'Sojabohnen, geröstet und gesalzen',
    es: 'Soja tostada y salada',
    fr: 'Soja grillé et salé',
    it: 'Soia tostata e salata',
    da: 'Sojabønner, ristede og saltede',
    bg: 'Печена солена соя',
  },
  'Soy flour, full-fat, raw': {
    en: 'Soy flour, full-fat',
    de: 'Sojamehl, vollfett',
    es: 'Harina de soja entera',
    fr: 'Farine de soja entière',
    it: 'Farina di soia integrale',
    da: 'Sojamel, fuldfedt',
    bg: 'Соево брашно, пълномаслено',
  },
  'Soy flour, low-fat': {
    en: 'Soy flour, low-fat',
    de: 'Sojamehl, fettarm',
    es: 'Harina de soja desgrasada',
    fr: 'Farine de soja allégée',
    it: 'Farina di soia magra',
    da: 'Sojamel, fedtfattigt',
    bg: 'Соево брашно, нискомаслено',
  },
  'Lupins, mature seeds, raw': {
    en: 'Lupin beans, dry',
    de: 'Lupinen, trocken',
    es: 'Altramuces secos',
    fr: 'Lupins secs',
    it: 'Lupini secchi',
    da: 'Lupinbønner, tørrede',
    bg: 'Лупина, суха',
  },
  'Winged beans, mature seeds, raw': {
    en: 'Winged beans, dry',
    de: 'Flügelbohnen, trocken',
    es: 'Judías aladas secas',
    fr: 'Haricots ailés secs',
    it: 'Fagioli alati secchi',
    da: 'Vingebønner, tørrede',
    bg: 'Крилат боб, сух',
  },
  'Tofu, salted and fermented (fuyu), prepared with calcium sulfate': {
    en: 'Fermented tofu (fuyu), set with calcium',
    de: 'Fermentierter Tofu (Fuyu), mit Calcium gefällt',
    es: 'Tofu fermentado (fuyu), cuajado con calcio',
    fr: 'Tofu fermenté (fuyu), coagulé au calcium',
    it: 'Tofu fermentato (fuyu), coagulato al calcio',
    da: 'Fermenteret tofu (fuyu), coaguleret med calcium',
    bg: 'Ферментирало тофу (фую), със сулфат на калция',
  },

  /* ---------------------------------------------------------- grains ── */
  'Wheat germ': {
    en: 'Wheat germ',
    de: 'Weizenkeime',
    es: 'Germen de trigo',
    fr: 'Germe de blé',
    it: 'Germe di grano',
    da: 'Hvedekim',
    bg: 'Пшеничен зародиш',
  },
  'Rice, white, short-grain, enriched, uncooked': {
    en: 'White short-grain rice, enriched, dry',
    de: 'Weißer Rundkornreis, angereichert, roh',
    es: 'Arroz blanco de grano corto, enriquecido, crudo',
    fr: 'Riz blanc rond, enrichi, cru',
    it: 'Riso bianco a chicco corto, arricchito, crudo',
    da: 'Hvide rundkornede ris, berigede, rå',
    bg: 'Бял късозърнест ориз, обогатен, суров',
  },
  'Cornmeal, white, self-rising, degermed, enriched': {
    en: 'White cornmeal, self-rising and enriched',
    de: 'Weißes Maismehl, backfertig und angereichert',
    es: 'Harina de maíz blanca, leudante y enriquecida',
    fr: 'Semoule de maïs blanche, à levure incorporée et enrichie',
    it: 'Farina di mais bianca, autolievitante e arricchita',
    da: 'Hvidt majsmel, selvhævende og beriget',
    bg: 'Бяло царевично брашно, самонабухващо и обогатено',
  },
  'Arrowroot, raw': {
    en: 'Arrowroot, raw',
    de: 'Pfeilwurz, roh',
    es: 'Arrurruz crudo',
    fr: 'Arrow-root cru',
    it: 'Maranta cruda',
    da: 'Pilerod, rå',
    bg: 'Арарут, суров',
  },
  'Bread, whole grain white, toasted': {
    en: 'Wholegrain white bread, toasted',
    de: 'Vollkorn-Weißbrot, getoastet',
    es: 'Pan blanco integral tostado',
    fr: 'Pain blanc complet grillé',
    it: 'Pane bianco integrale tostato',
    da: 'Fuldkornshvidt brød, ristet',
    bg: 'Пълнозърнест бял хляб, препечен',
  },
  'Macaroni or noodles with cheese, microwaveable, unprepared': {
    en: 'Macaroni cheese, dry mix',
    de: 'Makkaroni mit Käse, Trockenmischung',
    es: 'Macarrones con queso, mezcla seca',
    fr: 'Macaronis au fromage, mélange sec',
    it: 'Maccheroni al formaggio, preparato secco',
    da: 'Makaroni med ost, tørblanding',
    bg: 'Макарони със сирене, суха смес',
  },

  /* ------------------------------------------------------------ offal ── */
  'Beef, variety meats and by-products, spleen, raw': {
    en: 'Beef spleen, raw',
    de: 'Rindermilz, roh',
    es: 'Bazo de vacuno, crudo',
    fr: 'Rate de bœuf, crue',
    it: 'Milza di manzo, cruda',
    da: 'Oksemilt, rå',
    bg: 'Телешки далак, суров',
  },
  'Goose, liver, raw': {
    en: 'Goose liver, raw',
    de: 'Gänseleber, roh',
    es: 'Hígado de oca, crudo',
    fr: 'Foie d’oie, cru',
    it: 'Fegato d’oca, crudo',
    da: 'Gåselever, rå',
    bg: 'Гъши дроб, суров',
  },
  'Veal, variety meats and by-products, liver, raw': {
    en: 'Veal liver, raw',
    de: 'Kalbsleber, roh',
    es: 'Hígado de ternera, crudo',
    fr: 'Foie de veau, cru',
    it: 'Fegato di vitello, crudo',
    da: 'Kalvelever, rå',
    bg: 'Телешки черен дроб, суров',
  },
  'Lamb, New Zealand, imported, kidney, cooked, soaked and fried': {
    en: 'Lamb kidney, fried',
    de: 'Lammniere, gebraten',
    es: 'Riñón de cordero frito',
    fr: 'Rognon d’agneau poêlé',
    it: 'Rognone d’agnello in padella',
    da: 'Lammenyre, stegt',
    bg: 'Агнешки бъбрек, пържен',
  },
  'Chicken, capons, giblets, cooked, simmered': {
    en: 'Chicken giblets, simmered',
    de: 'Hühnerinnereien, gegart',
    es: 'Menudillos de pollo cocidos',
    fr: 'Abats de poulet mijotés',
    it: 'Frattaglie di pollo lessate',
    da: 'Kyllingekråse, kogt',
    bg: 'Пилешки дреболии, варени',
  },
  'Chicken, broilers or fryers, giblets, cooked, fried': {
    en: 'Chicken giblets, fried',
    de: 'Hühnerinnereien, gebraten',
    es: 'Menudillos de pollo fritos',
    fr: 'Abats de poulet poêlés',
    it: 'Frattaglie di pollo fritte',
    da: 'Kyllingekråse, stegt',
    bg: 'Пилешки дреболии, пържени',
  },
  'Turkey, whole, giblets, cooked, simmered': {
    en: 'Turkey giblets, simmered',
    de: 'Puteninnereien, gegart',
    es: 'Menudillos de pavo cocidos',
    fr: 'Abats de dinde mijotés',
    it: 'Frattaglie di tacchino lessate',
    da: 'Kalkunkråse, kogt',
    bg: 'Пуешки дреболии, варени',
  },
  Liverwurst: {
    en: 'Liver sausage',
    de: 'Leberwurst',
    es: 'Paté de hígado',
    fr: 'Pâté de foie',
    it: 'Salsiccia di fegato',
    da: 'Leverpostej',
    bg: 'Пастет от черен дроб',
  },

  /* ------------------------------------------------------------- meat ── */
  'Beef, chuck, short ribs, boneless, separable lean only, trimmed to 0" fat, select, cooked, braised':
    {
      en: 'Beef short ribs, lean, braised',
      de: 'Rinderquerrippe, mager, geschmort',
      es: 'Costilla de vacuno magra, estofada',
      fr: 'Plat de côtes de bœuf maigre, braisé',
      it: 'Costine di manzo magre, brasate',
      da: 'Oksespidsbryst, magert, braiseret',
      bg: 'Телешки къси ребра, постни, задушени',
    },
  'Beef, New Zealand, imported, brisket point end, separable lean only, cooked, braised': {
    en: 'Beef brisket, lean, braised',
    de: 'Rinderbrust, mager, geschmort',
    es: 'Pecho de vacuno magro, estofado',
    fr: 'Poitrine de bœuf maigre, braisée',
    it: 'Punta di petto di manzo magra, brasata',
    da: 'Oksebryst, magert, braiseret',
    bg: 'Телешки гърди, постни, задушени',
  },
  'Beef, plate steak, boneless, outside skirt, separable lean only, trimmed to 0" fat, choice, cooked, grilled':
    {
      en: 'Beef skirt steak, lean, grilled',
      de: 'Rinder-Saumsteak, mager, gegrillt',
      es: 'Entraña de vacuno magra, a la plancha',
      fr: 'Bavette de bœuf maigre, grillée',
      it: 'Diaframma di manzo magro, alla griglia',
      da: 'Okseslag, magert, grillet',
      bg: 'Телешки диафрагмен стек, постен, на скара',
    },
  'Veal, leg (top round), separable lean only, cooked, braised': {
    en: 'Veal topside, lean, braised',
    de: 'Kalbsoberschale, mager, geschmort',
    es: 'Babilla de ternera magra, estofada',
    fr: 'Noix de veau maigre, braisée',
    it: 'Fesa di vitello magra, brasata',
    da: 'Kalveinderlår, magert, braiseret',
    bg: 'Телешки бут, постен, задушен',
  },
  'Lamb, foreshank, separable lean only, trimmed to 1/4" fat, choice, cooked, braised': {
    en: 'Lamb shank, lean, braised',
    de: 'Lammhaxe, mager, geschmort',
    es: 'Jarrete de cordero magro, estofado',
    fr: 'Jarret d’agneau maigre, braisé',
    it: 'Stinco d’agnello magro, brasato',
    da: 'Lammeskank, magert, braiseret',
    bg: 'Агнешки джолан, постен, задушен',
  },
  'Lamb, shoulder, arm, separable lean only, trimmed to 1/4" fat, choice, cooked, braised': {
    en: 'Lamb shoulder, lean, braised',
    de: 'Lammschulter, mager, geschmort',
    es: 'Paletilla de cordero magra, estofada',
    fr: 'Épaule d’agneau maigre, braisée',
    it: 'Spalla d’agnello magra, brasata',
    da: 'Lammebov, magert, braiseret',
    bg: 'Агнешка плешка, постна, задушена',
  },
  'Mutton, cooked, roasted (Navajo)': {
    en: 'Mutton, roasted',
    de: 'Hammelfleisch, gebraten',
    es: 'Carne de oveja asada',
    fr: 'Mouton rôti',
    it: 'Carne di pecora arrosto',
    da: 'Fårekød, stegt',
    bg: 'Овнешко, печено',
  },
  'Pork, cured, bacon, cooked, microwaved': {
    en: 'Bacon, cooked',
    de: 'Frühstücksspeck, gebraten',
    es: 'Bacon cocinado',
    fr: 'Bacon cuit',
    it: 'Bacon cotto',
    da: 'Bacon, stegt',
    bg: 'Бекон, приготвен',
  },
  'Pork, fresh, spareribs, separable lean and fat, cooked, braised': {
    en: 'Pork spare ribs, braised',
    de: 'Schweinerippchen, geschmort',
    es: 'Costillar de cerdo estofado',
    fr: 'Travers de porc braisés',
    it: 'Costine di maiale brasate',
    da: 'Svineribben, braiserede',
    bg: 'Свински ребра, задушени',
  },
  'Pork jerky': {
    en: 'Pork jerky',
    de: 'Schweinefleisch-Trockenfleisch',
    es: 'Cecina de cerdo',
    fr: 'Viande de porc séchée',
    it: 'Carne di maiale essiccata',
    da: 'Tørret svinekød',
    bg: 'Сушено свинско месо',
  },
  'Chicken, broilers or fryers, breast, meat only, cooked, fried': {
    en: 'Chicken breast, skinless, fried',
    de: 'Hähnchenbrust, ohne Haut, gebraten',
    es: 'Pechuga de pollo sin piel, a la sartén',
    fr: 'Blanc de poulet sans peau, poêlé',
    it: 'Petto di pollo senza pelle, in padella',
    da: 'Kyllingebryst uden skind, stegt',
    bg: 'Пилешки гърди без кожа, пържени',
  },
  'Pheasant, cooked, total edible': {
    en: 'Pheasant, cooked',
    de: 'Fasan, gegart',
    es: 'Faisán cocinado',
    fr: 'Faisan cuit',
    it: 'Fagiano cotto',
    da: 'Fasan, tilberedt',
    bg: 'Фазан, приготвен',
  },

  /* ------------------------------------------------------- fish, shellfish */
  'Oysters, canned': {
    en: 'Oysters, canned',
    de: 'Austern, aus der Dose',
    es: 'Ostras en conserva',
    fr: 'Huîtres en conserve',
    it: 'Ostriche in scatola',
    da: 'Østers på dåse',
    bg: 'Стриди, консерва',
  },
  Mussels: {
    en: 'Mussels',
    de: 'Miesmuscheln',
    es: 'Mejillones',
    fr: 'Moules',
    it: 'Cozze',
    da: 'Blåmuslinger',
    bg: 'Миди',
  },
  Octopus: {
    en: 'Octopus',
    de: 'Krake',
    es: 'Pulpo',
    fr: 'Poulpe',
    it: 'Polpo',
    da: 'Blæksprutte',
    bg: 'Октопод',
  },
  'Mollusks, clam, mixed species, cooked, breaded and fried': {
    en: 'Clams, breaded and fried',
    de: 'Venusmuscheln, paniert und gebraten',
    es: 'Almejas rebozadas y fritas',
    fr: 'Palourdes panées et frites',
    it: 'Vongole impanate e fritte',
    da: 'Muslinger, paneret og stegt',
    bg: 'Миди, панирани и пържени',
  },
  'Mollusks, cuttlefish, mixed species, cooked, moist heat': {
    en: 'Cuttlefish, cooked',
    de: 'Sepia, gegart',
    es: 'Sepia cocida',
    fr: 'Seiche cuite',
    it: 'Seppia cotta',
    da: 'Sepia, tilberedt',
    bg: 'Сепия, приготвена',
  },
  'Crustaceans, crab, alaska king, cooked, moist heat': {
    en: 'Alaska king crab, cooked',
    de: 'Alaska-Königskrabbe, gegart',
    es: 'Cangrejo real de Alaska cocido',
    fr: 'Crabe royal d’Alaska cuit',
    it: 'Granchio reale dell’Alaska cotto',
    da: 'Alaskakongekrabbe, kogt',
    bg: 'Аляска кралски рак, сварен',
  },
  'Fish, halibut, Greenland, raw': {
    en: 'Greenland halibut, raw',
    de: 'Schwarzer Heilbutt, roh',
    es: 'Fletán negro crudo',
    fr: 'Flétan du Groenland cru',
    it: 'Ippoglosso nero crudo',
    da: 'Hellefisk, rå',
    bg: 'Гренландска камбала, сурова',
  },
  'Salmon, sockeye, canned, drained solids, without skin and bones': {
    en: 'Sockeye salmon, canned, drained',
    de: 'Rotlachs, aus der Dose, abgetropft',
    es: 'Salmón rojo en conserva, escurrido',
    fr: 'Saumon rouge en conserve, égoutté',
    it: 'Salmone rosso in scatola, sgocciolato',
    da: 'Rødlaks på dåse, afdryppet',
    bg: 'Сьомга нерка, консерва, отцедена',
  },
  'Fish, herring, Atlantic, kippered': {
    en: 'Kippered herring',
    de: 'Räucherhering',
    es: 'Arenque ahumado',
    fr: 'Hareng fumé',
    it: 'Aringa affumicata',
    da: 'Røget sild',
    bg: 'Пушена херинга',
  },
  'Fish, sardines, canned': {
    en: 'Sardines, canned',
    de: 'Sardinen, aus der Dose',
    es: 'Sardinas en conserva',
    fr: 'Sardines en conserve',
    it: 'Sardine in scatola',
    da: 'Sardiner på dåse',
    bg: 'Сардини, консерва',
  },
  Anchovies: {
    en: 'Anchovies',
    de: 'Sardellen',
    es: 'Anchoas',
    fr: 'Anchois',
    it: 'Acciughe',
    da: 'Ansjoser',
    bg: 'Аншоа',
  },
  Ceviche: {
    en: 'Ceviche',
    de: 'Ceviche',
    es: 'Ceviche',
    fr: 'Ceviche',
    it: 'Ceviche',
    da: 'Ceviche',
    bg: 'Севиче',
  },
  'Sushi, topped with eel': {
    en: 'Eel nigiri',
    de: 'Aal-Nigiri',
    es: 'Nigiri de anguila',
    fr: 'Nigiri à l’anguille',
    it: 'Nigiri all’anguilla',
    da: 'Ål-nigiri',
    bg: 'Нигири с змиорка',
  },
  'Flounder with crab stuffing': {
    en: 'Flounder with crab stuffing',
    de: 'Flunder mit Krebsfleischfüllung',
    es: 'Platija rellena de cangrejo',
    fr: 'Limande farcie au crabe',
    it: 'Passera ripiena di granchio',
    da: 'Skrubbe med krabbefyld',
    bg: 'Писия с пълнеж от раци',
  },
  'Seafood sauce': {
    en: 'Seafood sauce',
    de: 'Meeresfrüchtesauce',
    es: 'Salsa de marisco',
    fr: 'Sauce aux fruits de mer',
    it: 'Salsa di mare',
    da: 'Skaldyrssauce',
    bg: 'Сос от морски дарове',
  },

  /* --------------------------------------------------- dairy and eggs ── */
  'Cheese, parmesan, shredded': {
    en: 'Parmesan, grated',
    de: 'Parmesan, gerieben',
    es: 'Parmesano rallado',
    fr: 'Parmesan râpé',
    it: 'Parmigiano grattugiato',
    da: 'Parmesan, revet',
    bg: 'Пармезан, настърган',
  },
  'Cheese, parmesan, low sodium': {
    en: 'Parmesan, low salt',
    de: 'Parmesan, salzarm',
    es: 'Parmesano bajo en sal',
    fr: 'Parmesan à teneur réduite en sel',
    it: 'Parmigiano a basso contenuto di sale',
    da: 'Parmesan, saltfattig',
    bg: 'Пармезан, с намалена сол',
  },
  'Queso cotija': {
    en: 'Cotija cheese',
    de: 'Cotija-Käse',
    es: 'Queso cotija',
    fr: 'Fromage cotija',
    it: 'Formaggio cotija',
    da: 'Cotija-ost',
    bg: 'Сирене котиха',
  },
  'Cheese, American and Swiss blends': {
    en: 'Processed cheese blend',
    de: 'Schmelzkäsemischung',
    es: 'Mezcla de queso fundido',
    fr: 'Mélange de fromage fondu',
    it: 'Miscela di formaggio fuso',
    da: 'Smelteostblanding',
    bg: 'Топено сирене, смес',
  },
  'Egg, yolk, raw, frozen, pasteurized': {
    en: 'Egg yolk, pasteurised',
    de: 'Eigelb, pasteurisiert',
    es: 'Yema de huevo pasteurizada',
    fr: 'Jaune d’œuf pasteurisé',
    it: 'Tuorlo d’uovo pastorizzato',
    da: 'Æggeblomme, pasteuriseret',
    bg: 'Яйчен жълтък, пастьоризиран',
  },
  'Ghee (Clarified Butter)': {
    en: 'Ghee (clarified butter)',
    de: 'Ghee (Butterschmalz)',
    es: 'Ghee (mantequilla clarificada)',
    fr: 'Ghee (beurre clarifié)',
    it: 'Ghee (burro chiarificato)',
    da: 'Ghee (klaret smør)',
    bg: 'Гхи (избистрено масло)',
  },

  /* -------------------------------------------------- plants and other ── */
  'Mushrooms, brown, italian, or crimini, exposed to ultraviolet light, raw': {
    en: 'Chestnut mushrooms, UV-treated, raw',
    de: 'Braune Champignons, UV-behandelt, roh',
    es: 'Champiñones portobello jóvenes tratados con UV, crudos',
    fr: 'Champignons de Paris bruns traités aux UV, crus',
    it: 'Funghi cremini trattati ai raggi UV, crudi',
    da: 'Brune champignoner, UV-behandlede, rå',
    bg: 'Кафяви печурки, обработени с UV, сурови',
  },
  'Mushrooms, morel, raw': {
    en: 'Morels, raw',
    de: 'Morcheln, roh',
    es: 'Colmenillas crudas',
    fr: 'Morilles crues',
    it: 'Spugnole crude',
    da: 'Morkler, rå',
    bg: 'Смръчкули, сурови',
  },
  'Fireweed, leaves, raw': {
    en: 'Fireweed leaves, raw',
    de: 'Weidenröschenblätter, roh',
    es: 'Hojas de epilobio crudas',
    fr: 'Feuilles d’épilobe crues',
    it: 'Foglie di epilobio crude',
    da: 'Gederamsblade, rå',
    bg: 'Листа от върболика, сурови',
  },
  'Stinging Nettles, blanched (Northern Plains Indians)': {
    en: 'Nettles, blanched',
    de: 'Brennnesseln, blanchiert',
    es: 'Ortigas escaldadas',
    fr: 'Orties blanchies',
    it: 'Ortiche sbollentate',
    da: 'Brændenælder, blancherede',
    bg: 'Коприва, бланширана',
  },
  'Agave, cooked (Southwest)': {
    en: 'Agave, cooked',
    de: 'Agave, gegart',
    es: 'Agave cocido',
    fr: 'Agave cuit',
    it: 'Agave cotta',
    da: 'Agave, tilberedt',
    bg: 'Агаве, приготвено',
  },
  'Baking chocolate, unsweetened, squares': {
    en: 'Unsweetened baking chocolate',
    de: 'Ungesüßte Kuvertüre',
    es: 'Chocolate negro sin azúcar para repostería',
    fr: 'Chocolat noir non sucré à pâtisser',
    it: 'Cioccolato fondente non zuccherato',
    da: 'Usødet mørk chokolade',
    bg: 'Неподсладен шоколад за готвене',
  },
  'Nutritional drink or shake, liquid, soy-based': {
    en: 'Soy-based nutrition shake',
    de: 'Trinknahrung auf Sojabasis',
    es: 'Batido nutricional de soja',
    fr: 'Boisson nutritionnelle au soja',
    it: 'Bevanda nutrizionale a base di soia',
    da: 'Sojabaseret ernæringsdrik',
    bg: 'Хранителна напитка на соева основа',
  },
};
